export type LabId = "braking" | "robot" | "physics" | "model";
export type Domain =
  | "自驾与 ROS"
  | "具身与机器人"
  | "仿真与世界模型"
  | "3D 与数字孪生"
  | "AI 与数据"
  | "金融与生命科学";
export type SceneEntry = {
  id: string;
  title: string;
  domain: Domain;
  problem: string;
  engine: string;
  source: string;
  sourceLabel: string;
  input: string;
  output: string;
  runtime: string;
  priority: "P0" | "P1" | "P2";
  lab?: LabId;
};
export const scenes: SceneEntry[] = [
  {
    id: "braking",
    title: "制动距离实验室",
    domain: "自驾与 ROS",
    problem: "反应晚了 0.8 秒，会多走多远？比较车速、附着系数与反应延迟。",
    engine: "Three.js + 解析运动学",
    source: "https://threejs.org/",
    sourceLabel: "Three.js 引擎",
    input: "车速 / 距离 / 延迟 / 附着系数",
    output: "停止距离、碰撞状态、两组轨迹",
    runtime: "浏览器 · 本地计算",
    priority: "P0",
    lab: "braking",
  },
  {
    id: "ros-replay",
    title: "ROS 多传感器回放",
    domain: "自驾与 ROS",
    problem:
      "在同一时间轴检查点云、相机、TF 与控制信号，定位异常发生的那一帧。",
    engine: "Rerun Web Viewer + MCAP adapter",
    source: "https://rerun.io/docs/howto/integrations/embed-web",
    sourceLabel: "Rerun 嵌入文档",
    input: "MCAP / ROS bag / 图像 / TF",
    output: "同步回放、事件书签、证据片段",
    runtime: "浏览器 + 数据转换服务",
    priority: "P0",
  },
  {
    id: "calibration",
    title: "传感器对齐诊断",
    domain: "自驾与 ROS",
    problem: "区分时间不同步、外参偏差与模型误检，观察点云投影如何偏离图像。",
    engine: "Three.js + OpenCV + Rerun",
    source: "https://rerun.io/",
    sourceLabel: "Rerun 多模态引擎",
    input: "标定参数 / 点云 / 图像 / 时间戳",
    output: "投影叠加、残差、对齐前后对比",
    runtime: "浏览器 + Python",
    priority: "P0",
  },
  {
    id: "scenario",
    title: "危险场景回归",
    domain: "自驾与 ROS",
    problem: "复现切入、遮挡与行人横穿，用同一场景对比两个策略版本。",
    engine: "CARLA + ScenarioRunner",
    source: "https://carla.org/",
    sourceLabel: "CARLA 引擎与演示",
    input: "OpenDRIVE / OpenSCENARIO / seed",
    output: "碰撞、TTC、轨迹差异、场景记录",
    runtime: "GPU 服务 + 浏览器回放",
    priority: "P1",
  },
  {
    id: "robot",
    title: "机械臂可达性实验室",
    domain: "具身与机器人",
    problem:
      "目标位置是否可达？直接改变目标与关节角，观察正逆运动学与末端误差。",
    engine: "Three.js + 二连杆 FK / IK",
    source:
      "https://gkjohnson.github.io/urdf-loaders/javascript/example/bundle/",
    sourceLabel: "URDF 真实机器人演示",
    input: "关节角 / 目标坐标 / 连杆长度",
    output: "末端位置、可达性、求解误差",
    runtime: "浏览器 · 本地计算",
    priority: "P0",
    lab: "robot",
  },
  {
    id: "robot-data",
    title: "机器人示教数据检查",
    domain: "具身与机器人",
    problem: "在训练前发现重复片段、动作跳变、无效示教与摄像头缺帧。",
    engine: "LeRobot + Rerun",
    source:
      "https://huggingface.co/docs/lerobot/main/en/getting_started_real_world_robot",
    sourceLabel: "LeRobot 数据与回放",
    input: "LeRobot episodes / video / actions",
    output: "片段标注、动作曲线、质量报告",
    runtime: "数据转换服务 + Web Viewer",
    priority: "P0",
  },
  {
    id: "policy",
    title: "机器人策略对比",
    domain: "具身与机器人",
    problem: "固定任务和随机种子，比较策略成功率、接触行为与失败步骤。",
    engine: "MuJoCo / Isaac Lab + Rerun",
    source: "https://playground.mujoco.org/",
    sourceLabel: "MuJoCo Playground 演示",
    input: "MJCF / 策略检查点 / 实验配置",
    output: "同步轨迹、接触、成功率分布",
    runtime: "Python / GPU + 浏览器",
    priority: "P1",
  },
  {
    id: "ros-graph",
    title: "ROS 通信与坐标树",
    domain: "具身与机器人",
    problem: "找到断开的 TF 链、异常 Topic 频率和 QoS 不匹配。",
    engine: "ROS 2 + Foxglove + 图视图",
    source: "https://docs.foxglove.dev/docs/getting-started/frameworks/ros2",
    sourceLabel: "Foxglove ROS 2 接入",
    input: "ROS graph / TF / QoS / topic stats",
    output: "坐标树、连接诊断、频率与延迟",
    runtime: "只读 ROS bridge + Web",
    priority: "P1",
  },
  {
    id: "physics",
    title: "碰撞与材料实验室",
    domain: "仿真与世界模型",
    problem: "改变材料弹性和重力，观察真实刚体求解器如何计算落体与碰撞。",
    engine: "Rapier WASM + Three.js",
    source: "https://rapier.rs/",
    sourceLabel: "Rapier 物理引擎",
    input: "重力 / 恢复系数 / 初始高度",
    output: "落体轨迹、反弹高度、运行时间",
    runtime: "浏览器 · WASM 物理求解",
    priority: "P0",
    lab: "physics",
  },
  {
    id: "gazebo",
    title: "机器人传感器仿真",
    domain: "仿真与世界模型",
    problem: "在部署机器人之前检查传感器位置、观测范围与 ROS 数据链路。",
    engine: "Gazebo + ros_gz + Rerun",
    source: "https://gazebosim.org/docs/latest/ros2_integration/",
    sourceLabel: "Gazebo / ROS 2 官方示例",
    input: "SDF / URDF / 传感器配置",
    output: "传感器回放、坐标系与场景状态",
    runtime: "原生仿真服务 + 浏览器",
    priority: "P1",
  },
  {
    id: "world-model",
    title: "世界模型分支对比",
    domain: "仿真与世界模型",
    problem: "同一初始条件下比较不同动作生成的未来，检查时序一致性和物理异常。",
    engine: "NVIDIA Cosmos + Isaac Sim",
    source: "https://www.nvidia.com/en-us/ai/cosmos/",
    sourceLabel: "Cosmos 官方动态演示",
    input: "视频 / 控制条件 / seed / 模型版本",
    output: "未来分支、条件记录、对比标注",
    runtime: "GPU 推理 + 视频/3D 回放",
    priority: "P2",
  },
  {
    id: "worldsim",
    title: "驾驶模拟器结果工作台",
    domain: "仿真与世界模型",
    problem: "把驾驶模拟器输出、控制输入与场景事件放在同一视图中复盘。",
    engine: "VI-WorldSim / Unreal + 结果适配器",
    source: "https://www.vi-grade.com/en/products/vi-worldsim/",
    sourceLabel: "VI-WorldSim 官方演示",
    input: "授权模拟器导出 / 车辆信号 / 视频",
    output: "事件回放、控制曲线、运行对比",
    runtime: "授权原生服务 · 非浏览器引擎",
    priority: "P2",
  },
  {
    id: "model",
    title: "3D 资产检查器",
    domain: "3D 与数字孪生",
    problem:
      "把本地 GLB 放进浏览器检查结构、材质和动画，判断资产能否用于产品展示。",
    engine: "Three.js GLTFLoader",
    source: "https://modelviewer.dev/editor/",
    sourceLabel: "model-viewer 真实模型编辑器",
    input: "自包含 GLB / 动画 / 材质",
    output: "模型树、动画播放、包围盒尺寸",
    runtime: "浏览器 · 文件不上传",
    priority: "P0",
    lab: "model",
  },
  {
    id: "vehicles",
    title: "汽车结构与配置对比",
    domain: "3D 与数字孪生",
    problem: "从外观旋转升级到部件选择、配置差异、空间尺寸与传感器视野比较。",
    engine: "Three.js / Babylon Viewer / model-viewer",
    source: "https://www.babylonjs.com/viewer/",
    sourceLabel: "Babylon 真实 3D Viewer",
    input: "授权车辆 GLB / 部件树 / 官方参数",
    output: "部件高亮、配置对比、尺寸说明",
    runtime: "浏览器 · 品牌模型需授权",
    priority: "P1",
  },
  {
    id: "splat",
    title: "真实空间重建与巡检",
    domain: "3D 与数字孪生",
    problem:
      "检查重建空洞、残影与覆盖盲区，为场地勘查和机器人环境复现提供空间依据。",
    engine: "Spark / SuperSplat",
    source: "https://superspl.at/editor",
    sourceLabel: "SuperSplat 在线引擎",
    input: "PLY / SPZ / splat / 相机位姿",
    output: "重建检查、标注、视角记录",
    runtime: "浏览器 · GPU 渲染",
    priority: "P1",
  },
  {
    id: "geospatial",
    title: "城市与交通数字孪生",
    domain: "3D 与数字孪生",
    problem: "比较路网、车辆流量与场地布局，找出拥堵和设施覆盖盲区。",
    engine: "CesiumJS + SUMO",
    source: "https://cesium.com/platform/cesiumjs/",
    sourceLabel: "CesiumJS 引擎与案例",
    input: "3D Tiles / GeoJSON / SUMO trajectories",
    output: "城市轨迹、拥堵时段、方案对比",
    runtime: "浏览器 + CPU 交通仿真",
    priority: "P1",
  },
  {
    id: "ai-traces",
    title: "AI Agent 运行诊断",
    domain: "AI 与数据",
    problem:
      "一次回答为什么慢、为什么错？关联模型调用、检索证据、工具失败和成本。",
    engine: "OpenTelemetry / Phoenix + 时间轴",
    source: "https://arize.com/docs/phoenix",
    sourceLabel: "Phoenix 追踪与评估引擎",
    input: "OTLP spans / evals / 检索片段",
    output: "调用瀑布图、失败节点、版本差异",
    runtime: "采集服务 + 浏览器",
    priority: "P0",
  },
  {
    id: "model-graph",
    title: "神经网络结构检查",
    domain: "AI 与数据",
    problem: "查看模型的张量形状和算子连接，定位结构不匹配或转换问题。",
    engine: "Netron",
    source: "https://netron.app/",
    sourceLabel: "打开 Netron 实际引擎",
    input: "ONNX / TFLite / 支持的模型文件",
    output: "算子图、张量结构、节点属性",
    runtime: "本地或浏览器 Viewer",
    priority: "P1",
  },
  {
    id: "embedding",
    title: "训练数据覆盖与离群检查",
    domain: "AI 与数据",
    problem:
      "从大量样本中发现重复簇、稀缺场景和标注疑点，把选择结果回到原始样本。",
    engine: "UMAP + WebGL scatter / DuckDB-WASM",
    source: "https://pair-code.github.io/understanding-umap/",
    sourceLabel: "UMAP 交互式真实演示",
    input: "embeddings / labels / sample ids",
    output: "样本选择、相似簇、覆盖缺口",
    runtime: "Worker / WASM + 浏览器",
    priority: "P1",
  },
  {
    id: "lineage",
    title: "数据处理链路与版本差异",
    domain: "AI 与数据",
    problem: "某批数据或模型结果发生变化时，追溯源数据、处理任务和版本依赖。",
    engine: "Sigma.js + OpenLineage adapter",
    source: "https://www.sigmajs.org/",
    sourceLabel: "Sigma.js WebGL 图引擎",
    input: "任务事件 / dataset versions / lineage",
    output: "影响路径、失败上游、版本对比",
    runtime: "图数据 API + 浏览器",
    priority: "P2",
  },
  {
    id: "crypto",
    title: "策略回测与市场微观结构",
    domain: "金融与生命科学",
    problem: "同时查看交易、成本、滑点和回撤，解释策略收益来自哪里、何时失效。",
    engine: "Lightweight Charts + DuckDB-WASM",
    source: "https://tradingview.github.io/lightweight-charts/",
    sourceLabel: "Lightweight Charts 实际引擎",
    input: "OHLCV / 成交 / 订单簿 / 回测结果",
    output: "交易归因、资金曲线、样本外比较",
    runtime: "浏览器 + 回测服务",
    priority: "P1",
  },
  {
    id: "supply-chain",
    title: "产业链证据与风险传导",
    domain: "金融与生命科学",
    problem: "每条上下游关系都能追到出处，模拟供应商受影响时的关联范围。",
    engine: "Sigma.js + Graphology / ECharts",
    source: "https://www.sigmajs.org/",
    sourceLabel: "Sigma.js 关系图引擎",
    input: "实体 / 关系 / 出处 / 有效时间",
    output: "证据图谱、路径查询、假设冲击",
    runtime: "图数据服务 + 浏览器",
    priority: "P1",
  },
  {
    id: "anatomy",
    title: "人体结构与运动理解",
    domain: "金融与生命科学",
    problem: "把解剖结构、关节运动与局部标注关联起来，辅助学习和沟通。",
    engine: "Three.js / VTK.js / Cornerstone3D",
    source: "https://cornerstonejs.org/docs/examples/",
    sourceLabel: "Cornerstone3D 真实影像演示",
    input: "授权人体网格 / 关节 / 去标识影像",
    output: "结构定位、剖切、运动说明",
    runtime: "浏览器 · 不提供疾病诊断",
    priority: "P1",
  },
  {
    id: "engineering",
    title: "热场、流场与工程结果",
    domain: "3D 与数字孪生",
    problem: "查看车辆、电池或设备的热热点、流场路径与不同工况的差异。",
    engine: "VTK.js / ParaView",
    source: "https://kitware.github.io/vtk-js/docs/",
    sourceLabel: "VTK.js 科学可视化引擎",
    input: "VTK / VTI / VTU / 求解器结果",
    output: "切片、等值面、流线与工况对比",
    runtime: "求解器后台 + 浏览器后处理",
    priority: "P2",
  },
];
export const domains = Array.from(new Set(scenes.map((s) => s.domain)));
export const labs = scenes.filter((s): s is SceneEntry & { lab: LabId } =>
  Boolean(s.lab),
);
