// One distinct procedural sketch per scene (keyed by scene id). Each captures what that scene computes.
import { Scene3, armPose, STEEL, DARK, CYAN, AMBER, GREEN, VIOLET, type V3 } from "./mini3d";

export type Draw = (ctx: CanvasRenderingContext2D, w: number, h: number, t: number, r: () => number) => void;
const C = { live: "#5ee7ff", ref: "#ffb454", ok: "#7cf3a0", bad: "#ff5d73", violet: "#b99cff", muted: "#7e90a8", fg: "#e6eef8", line: "#1c2a3d", panel: "rgba(13,20,32,0.9)" };
const plot = (ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, f: (u: number) => number, col: string, cursor?: number) => { ctx.fillStyle = C.panel; ctx.fillRect(x, y, w, h); ctx.strokeStyle = C.line; ctx.strokeRect(x + 0.5, y + 0.5, w - 1, h - 1); ctx.strokeStyle = col; ctx.lineWidth = 1.5; ctx.beginPath(); for (let i = 0; i <= 60; i++) { const u = i / 60; const v = f(u); const px = x + 4 + u * (w - 8), py = y + h - 4 - Math.max(0, Math.min(1, v)) * (h - 8); i ? ctx.lineTo(px, py) : ctx.moveTo(px, py); } ctx.stroke(); ctx.lineWidth = 1; if (cursor !== undefined) { ctx.strokeStyle = C.fg; ctx.beginPath(); ctx.moveTo(x + 4 + cursor * (w - 8), y); ctx.lineTo(x + 4 + cursor * (w - 8), y + h); ctx.stroke(); } };
const car = (ctx: CanvasRenderingContext2D, x: number, y: number, a: number, col: string, s = 1) => { ctx.save(); ctx.translate(x, y); ctx.rotate(a); ctx.fillStyle = col; ctx.fillRect(-9 * s, -4 * s, 18 * s, 8 * s); ctx.restore(); };
const road = (ctx: CanvasRenderingContext2D, w: number, h: number, lanes = 3) => { ctx.fillStyle = "#0b1320"; ctx.fillRect(0, h * 0.3, w, h * 0.4); ctx.strokeStyle = "#3a4c66"; ctx.setLineDash([8, 8]); for (let i = 1; i < lanes; i++) { const y = h * 0.3 + (h * 0.4 * i) / lanes; ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); } ctx.setLineDash([]); };
const heat = (v: number) => (v < 0.5 ? `rgb(${12 + v * 164},${22 + v * 418},${40 + v * 430})` : `rgb(${94 + (v - 0.5) * 322},${231 - (v - 0.5) * 276},${255 - (v - 0.5) * 280})`);


// ── 3-D scenes (software renderer) ─────────────────────────
const humanoid = (sc: Scene3, t: number, push: boolean) => {
  const lean = Math.sin(t * 1.1) * 0.16 + (push ? 0.3 : 0);
  const hip: V3 = [lean * 1.1, 1.55, 0];
  const chest: V3 = [hip[0] + lean * 0.5, hip[1] + 0.62, 0];
  sc.shadow([hip[0] * 0.5, 0, 0], 0.7, 0.5);
  sc.limb(hip, chest, 0.26, STEEL, 8);
  sc.sphere([chest[0] + lean * 0.15, chest[1] + 0.42, 0], 0.24, STEEL);
  for (const s of [-1, 1]) {
    const knee: V3 = [hip[0] + lean * 0.5, hip[1] - 0.66, s * 0.22];
    const foot: V3 = [lean * 0.2, 0.08, s * 0.24];
    sc.limb([hip[0], hip[1] - 0.06, s * 0.2], knee, 0.16, STEEL);
    sc.limb(knee, foot, 0.13, STEEL);
    sc.box([foot[0] + 0.08, 0.05, foot[2]], [0.42, 0.1, 0.22], DARK);
    const el: V3 = [chest[0] + Math.sin(t * 1.7 + s) * 0.25, chest[1] - 0.42, s * 0.4];
    sc.limb([chest[0], chest[1] + 0.16, s * 0.32], el, 0.12, STEEL);
    sc.limb(el, [el[0] + Math.sin(t * 1.7 + s) * 0.2, el[1] - 0.42, s * 0.42], 0.1, STEEL);
  }
  sc.sphere([hip[0], hip[1] + 0.25, 0], 0.13, GREEN);
};

const scene3Preview = (build: (sc: Scene3, t: number, r: () => number) => void, cam?: Partial<{ yaw: number; pitch: number; dist: number; target: V3; spin: number }>): Draw =>
  (ctx, w, h, t, r) => {
    const sc = new Scene3(cam?.yaw ?? 0.7, cam?.pitch ?? 0.3, cam?.dist ?? 9, cam?.target ?? [0, 1, 0]);
    sc.yaw += t * (cam?.spin ?? 0.12);
    const g = ctx.createLinearGradient(0, 0, 0, h); g.addColorStop(0, "#080d16"); g.addColorStop(1, "#0d1522"); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h);
    sc.grid(5, 1);
    build(sc, t, r);
    sc.render(ctx, w, h);
  };

export const scenePreviews: Record<string, Draw> = {
  // driving
  perception: (ctx, w, h, t, r) => { const cx = w * 0.5, cy = h * 0.55; const a = t * 1.8; for (let i = 0; i < 260; i++) { const ang = (i / 260) * Math.PI * 2; const d = (((ang - a) % (Math.PI * 2)) + Math.PI * 2) % (Math.PI * 2); const rr = 0.3 + r() * 0.65; ctx.fillStyle = `rgba(94,231,255,${(1 - d / 6.3) * 0.9})`; ctx.fillRect(cx + Math.cos(ang) * rr * w * 0.48, cy + Math.sin(ang) * rr * h * 0.4, 2, 2); } ctx.strokeStyle = "rgba(94,231,255,0.5)"; ctx.beginPath(); ctx.moveTo(cx, cy); ctx.lineTo(cx + Math.cos(a) * w, cy + Math.sin(a) * h); ctx.stroke(); car(ctx, cx, cy, 0, C.ref); [[0.2, 0.3], [0.75, 0.4], [0.6, 0.85]].forEach(([x, y], i) => { ctx.strokeStyle = C.ok; ctx.strokeRect(w * x - 10 + Math.sin(t + i) * 4, h * y - 6, 20, 12); }); ctx.fillStyle = C.panel; ctx.fillRect(w - 52, 8, 44, 44); for (let gy = 0; gy < 8; gy++) for (let gx = 0; gx < 8; gx++) { if (r() < 0.25) { ctx.fillStyle = C.live; ctx.fillRect(w - 50 + gx * 5, 10 + gy * 5, 4, 4); } } },
  planning: (ctx, w, h, t) => { road(ctx, w, h); const ex = w * 0.2, ey = h * 0.5; for (let k = -3; k <= 3; k++) { ctx.strokeStyle = k === 1 ? C.ok : "rgba(126,144,168,0.35)"; ctx.lineWidth = k === 1 ? 2.5 : 1; ctx.beginPath(); ctx.moveTo(ex, ey); ctx.bezierCurveTo(ex + w * 0.3, ey, ex + w * 0.4, ey + k * 11, ex + w * 0.7, ey + k * 11); ctx.stroke(); } ctx.lineWidth = 1; car(ctx, ex, ey, 0, C.ref); car(ctx, w * 0.62 + Math.sin(t) * 6, h * 0.5 - 13 + Math.max(0, Math.sin(t * 0.8)) * 10, 0, C.live); const ttc = 1.5 + Math.sin(t) * 0.5; ctx.fillStyle = C.fg; ctx.font = "10px monospace"; ctx.fillText(`TTC ${ttc.toFixed(1)}s`, w * 0.62, h * 0.28); },
  "log-replay": (ctx, w, h, t) => { const n = 5; for (let i = 0; i < n; i++) { const y = 10 + i * ((h - 40) / n); plot(ctx, 10, y, w - 20, (h - 40) / n - 4, (u) => 0.5 + 0.35 * Math.sin(u * (6 + i * 3) + i + t * 0.5), [C.live, C.ref, C.ok, C.violet, C.bad][i], (t * 0.15) % 1); } ctx.fillStyle = C.panel; ctx.fillRect(10, h - 26, w - 20, 16); ctx.fillStyle = C.live; ctx.fillRect(10, h - 26, (w - 20) * ((t * 0.15) % 1), 16); ctx.fillStyle = C.fg; ctx.font = "9px monospace"; ctx.fillText(`${((t * 0.15) % 1 * 30).toFixed(1)} / 30.0 s · .mcap`, 14, h - 14); },
  calibration: (ctx, w, h, t, r) => { ctx.fillStyle = "#0a0f18"; ctx.fillRect(0, 0, w, h); for (let cx = 0; cx < 8; cx++) for (let cy = 0; cy < 4; cy++) { ctx.fillStyle = (cx + cy) % 2 ? "#cdd7e4" : "#2a3648"; ctx.fillRect(w * 0.15 + cx * w * 0.0875, h * 0.2 + cy * h * 0.15, w * 0.0875, h * 0.15); } const dx = Math.sin(t * 0.7) * 10, dy = Math.cos(t * 0.5) * 5; for (let i = 0; i < 200; i++) { const x = w * 0.15 + r() * w * 0.7, y = h * 0.2 + r() * h * 0.6; const onEdge = Math.abs(((x - w * 0.15) / (w * 0.0875)) % 1 - 0.5) > 0.45; ctx.fillStyle = onEdge ? C.bad : C.live; ctx.fillRect(x + dx, y + dy, 2, 2); } ctx.fillStyle = C.fg; ctx.font = "10px monospace"; ctx.fillText(`Δyaw ${(dx / 10).toFixed(2)}° · residual ${(Math.abs(dx) + Math.abs(dy)).toFixed(1)} px`, 8, h - 8); },
  "hd-map": (ctx, w, h, t) => { const pts: [number, number][] = []; for (let i = 0; i <= 80; i++) { const u = (i / 80) * Math.PI * 2; pts.push([w * 0.5 + Math.cos(u) * w * 0.34 + Math.cos(u * 2) * 8, h * 0.5 + Math.sin(u) * h * 0.32]); } for (const [off, col, dash] of [[-10, "#3a4c66", true], [0, "#5ee7ff", false], [10, "#3a4c66", true]] as const) { ctx.strokeStyle = col; ctx.setLineDash(dash ? [4, 4] : []); ctx.beginPath(); pts.forEach(([x, y], i) => { const px = x + (off * (x - w / 2)) / (w * 0.34), py = y + (off * (y - h / 2)) / (h * 0.32); i ? ctx.lineTo(px, py) : ctx.moveTo(px, py); }); ctx.closePath(); ctx.stroke(); } ctx.setLineDash([]); const k = Math.floor((t * 12) % 80); const [x, y] = pts[k], [x2, y2] = pts[(k + 1) % 80]; car(ctx, x, y, Math.atan2(y2 - y, x2 - x), C.ref); ctx.strokeStyle = C.ok; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(pts[(k + 5) % 80][0], pts[(k + 5) % 80][1]); ctx.lineTo(w * 0.92, h * 0.85); ctx.stroke(); ctx.lineWidth = 1; },
  // triage
  "event-mining": (ctx, w, h, t, r) => { for (let l = 0; l < 6; l++) { const y = 10 + l * ((h - 20) / 6); ctx.fillStyle = C.panel; ctx.fillRect(40, y, w - 50, (h - 20) / 6 - 4); ctx.fillStyle = C.muted; ctx.font = "9px monospace"; ctx.fillText(`veh ${l + 1}`, 6, y + 10); for (let k = 0; k < 5; k++) { const x = 40 + r() * (w - 50); ctx.fillStyle = [C.bad, C.ref, C.violet, C.live][Math.floor(r() * 4)]; ctx.beginPath(); ctx.moveTo(x, y + 2); ctx.lineTo(x + 4, y + 8); ctx.lineTo(x, y + 14); ctx.lineTo(x - 4, y + 8); ctx.closePath(); ctx.fill(); } } const cx = 40 + ((t * 25) % (w - 50)); ctx.strokeStyle = C.fg; ctx.beginPath(); ctx.moveTo(cx, 6); ctx.lineTo(cx, h - 6); ctx.stroke(); plot(ctx, 40, h * 0.74, w - 50, h * 0.24, (u) => 0.5 + 0.35 * Math.sin(u * 9 + t) - (Math.abs(u - 0.55) < 0.05 ? 0.4 : 0), C.live, ((t * 25) % (w - 50)) / (w - 50)); },
  review: (ctx, w, h, t) => { ctx.fillStyle = C.panel; ctx.fillRect(0, 0, w * 0.32, h); for (let i = 0; i < 8; i++) { const on = i === Math.floor(t) % 8; ctx.fillStyle = on ? "rgba(94,231,255,0.2)" : "transparent"; ctx.fillRect(4, 6 + i * 16, w * 0.32 - 8, 14); ctx.fillStyle = on ? C.fg : C.muted; ctx.font = "9px monospace"; ctx.fillText(`${String(i + 1).padStart(2, "0")} hard brake`, 8, 16 + i * 16); ctx.fillStyle = [C.bad, C.muted, C.ref][i % 3]; ctx.beginPath(); ctx.arc(w * 0.32 - 12, 13 + i * 16, 3, 0, Math.PI * 2); ctx.fill(); } const ox = w * 0.32; ctx.strokeStyle = C.live; ctx.beginPath(); ctx.moveTo(ox + 10, h * 0.8); ctx.quadraticCurveTo(ox + w * 0.3, h * 0.2, w - 10, h * 0.4); ctx.stroke(); const s = (t * 0.3) % 1; const u = 1 - s; const px = u * u * (ox + 10) + 2 * u * s * (ox + w * 0.3) + s * s * (w - 10), py = u * u * h * 0.8 + 2 * u * s * h * 0.2 + s * s * h * 0.4; car(ctx, px, py, -0.6, C.ref); ctx.strokeStyle = C.bad; ctx.beginPath(); ctx.arc(ox + w * 0.42, h * 0.42, 8 + Math.sin(t * 4) * 2, 0, Math.PI * 2); ctx.stroke(); },
  "log-sim": (ctx, w, h, t) => { road(ctx, w, h, 2); const x0 = w * 0.15; const dis = w * 0.5; ctx.fillStyle = "rgba(255,93,115,0.4)"; ctx.fillRect(dis - 1, h * 0.3, 2, h * 0.4); const s = (t * 0.25) % 1; const hx = x0 + s * w * 0.7; car(ctx, Math.min(hx, dis + (hx - dis) * 0.5), h * 0.4, 0, C.ref); const sx = hx; const sy = h * 0.6 - (hx > dis ? Math.min(1, (hx - dis) / 40) * 10 : 0); car(ctx, sx, sy, 0, C.live); car(ctx, w * 0.85, h * 0.6, 0, C.violet); ctx.strokeStyle = C.live; ctx.setLineDash([3, 3]); ctx.beginPath(); ctx.moveTo(dis, h * 0.6); ctx.lineTo(w * 0.9, h * 0.5); ctx.stroke(); ctx.setLineDash([]); ctx.fillStyle = C.fg; ctx.font = "9px monospace"; ctx.fillText("recorded ↑   counterfactual ↓", w * 0.15, h * 0.2); },
  dashboard: (ctx, w, h, t, r) => { const n = 20; const bw = (w * 0.6 - 20) / n; for (let i = 0; i < n; i++) { let y = h - 12; [C.live, C.ok, C.violet, C.ref].forEach((c, k) => { const hh = (h * 0.6) * Math.exp(-i / 12) * [0.4, 0.3, 0.15, k === 3 && i > 14 ? 0.5 : 0.15][k] * (0.8 + r() * 0.4); ctx.fillStyle = c; ctx.fillRect(10 + i * bw, y - hh, bw - 2, hh); y -= hh; }); } for (let i = 0; i < 30; i++) { const x = w * 0.65 + r() * w * 0.32, y = 10 + r() * (h - 20); const hh = 4 + r() * 20 * (0.7 + 0.3 * Math.sin(t * 2 + i)); ctx.fillStyle = hh > 16 ? C.bad : hh > 9 ? C.ref : C.live; ctx.fillRect(x - 3, y - hh, 6, hh); } },
  // geo
  deckgl: (ctx, w, h, t, r) => { for (let i = 0; i < 70; i++) { const x = 10 + r() * (w - 20), y = 10 + r() * (h - 20); const v = r(); const hh = 6 + v * 30 * (0.8 + 0.2 * Math.sin(t * 2 + i)); ctx.fillStyle = heat(v); ctx.globalAlpha = 0.85; ctx.beginPath(); ctx.moveTo(x - 5, y); ctx.lineTo(x, y - 3); ctx.lineTo(x + 5, y); ctx.lineTo(x + 5, y - hh); ctx.lineTo(x, y - hh - 3); ctx.lineTo(x - 5, y - hh); ctx.closePath(); ctx.fill(); } ctx.globalAlpha = 1; for (let i = 0; i < 4; i++) { const x0 = r() * w, y0 = r() * h, x1 = r() * w, y1 = r() * h; ctx.strokeStyle = C.ref; ctx.beginPath(); ctx.moveTo(x0, y0); ctx.quadraticCurveTo((x0 + x1) / 2, Math.min(y0, y1) - 30, x1, y1); ctx.stroke(); } },
  maplibre: (ctx, w, h, t) => { for (let y = 0; y < h; y += 6) { ctx.strokeStyle = `rgba(94,231,255,${0.08 + 0.12 * Math.abs(Math.sin(y * 0.1 + t))})`; ctx.beginPath(); for (let x = 0; x <= w; x += 6) { const z = Math.sin(x * 0.05 + t * 0.3) * 6 + Math.cos((x + y) * 0.08) * 5; x ? ctx.lineTo(x, y - z) : ctx.moveTo(x, y - z); } ctx.stroke(); } for (let i = 0; i < 8; i++) { const x = w * 0.2 + i * w * 0.08, bh = 14 + ((i * 7) % 5) * 6; ctx.fillStyle = heat(0.3 + (i % 4) * 0.15); ctx.fillRect(x, h * 0.6 - bh, 10, bh); ctx.fillStyle = "rgba(255,255,255,0.2)"; ctx.fillRect(x, h * 0.6 - bh, 10, 2); } },
  mapbox: (ctx, w, h, t) => { const cx = w / 2, cy = h / 2, R = Math.min(w, h) * 0.4; const grd = ctx.createRadialGradient(cx - R * 0.3, cy - R * 0.3, R * 0.2, cx, cy, R); grd.addColorStop(0, "#1e3a5f"); grd.addColorStop(1, "#070b12"); ctx.fillStyle = grd; ctx.beginPath(); ctx.arc(cx, cy, R, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = "rgba(94,231,255,0.25)"; for (let k = -2; k <= 2; k++) { ctx.beginPath(); ctx.ellipse(cx, cy, R * Math.abs(Math.cos(t * 0.3 + k * 0.6)), R, 0, 0, Math.PI * 2); ctx.stroke(); ctx.beginPath(); ctx.ellipse(cx, cy + k * R * 0.35, R * Math.sqrt(Math.max(0, 1 - (k * 0.35) ** 2)), R * 0.12, 0, 0, Math.PI * 2); ctx.stroke(); } for (let i = 0; i < 12; i++) { const a = t * 0.3 + i; const x = cx + Math.cos(a) * R * 0.85, y = cy + Math.sin(i * 1.7) * R * 0.6; if (Math.sin(a) > 0) { ctx.fillStyle = C.live; ctx.beginPath(); ctx.arc(x, y, 3, 0, Math.PI * 2); ctx.fill(); } } ctx.strokeStyle = "rgba(94,231,255,0.4)"; ctx.lineWidth = 6; ctx.beginPath(); ctx.arc(cx, cy, R + 4, 0, Math.PI * 2); ctx.stroke(); ctx.lineWidth = 1; },
  loca: (ctx, w, h, t) => { for (let i = 0; i < 14; i++) { const x = 20 + i * ((w - 40) / 14), bh = 20 + ((i * 13) % 7) * 8; const g = ctx.createLinearGradient(0, h - bh, 0, h); g.addColorStop(0, "#5ee7ff"); g.addColorStop(1, "#0c1628"); ctx.fillStyle = g; ctx.fillRect(x, h - 8 - bh, 12, bh); } const pts = [[0.1, 0.8], [0.3, 0.5], [0.5, 0.6], [0.7, 0.3], [0.9, 0.45]]; ctx.strokeStyle = "rgba(94,231,255,0.3)"; ctx.lineWidth = 3; ctx.beginPath(); pts.forEach(([x, y], i) => (i ? ctx.lineTo(x * w, y * h) : ctx.moveTo(x * w, y * h))); ctx.stroke(); ctx.lineWidth = 1; const s = (t * 0.4) % 1; const seg = Math.min(pts.length - 2, Math.floor(s * (pts.length - 1))); const f = s * (pts.length - 1) - seg; const hx = (pts[seg][0] + (pts[seg + 1][0] - pts[seg][0]) * f) * w, hy = (pts[seg][1] + (pts[seg + 1][1] - pts[seg][1]) * f) * h; ctx.fillStyle = C.ref; ctx.beginPath(); ctx.arc(hx, hy, 5, 0, Math.PI * 2); ctx.fill(); pts.forEach(([x, y], i) => { ctx.strokeStyle = C.bad; ctx.beginPath(); ctx.arc(x * w, y * h, 6 + ((t * 20 + i * 5) % 12), 0, Math.PI * 2); ctx.stroke(); }); },
  l7: (ctx, w, h, t, r) => { const cols = 9, rows = 6; for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) { const cx = 14 + x * ((w - 28) / cols) + (y % 2) * 8, cy = 14 + y * ((h - 28) / rows); const v = r() * (0.7 + 0.3 * Math.sin(t + x + y)); ctx.fillStyle = heat(v); ctx.beginPath(); for (let k = 0; k < 6; k++) { const a = (k / 6) * Math.PI * 2 + Math.PI / 6; k ? ctx.lineTo(cx + Math.cos(a) * 8, cy + Math.sin(a) * 8) : ctx.moveTo(cx + Math.cos(a) * 8, cy + Math.sin(a) * 8); } ctx.closePath(); ctx.fill(); } },
  cesium: (ctx, w, h, t) => { const cx = w / 2, cy = h * 0.55, R = Math.min(w, h) * 0.32; ctx.fillStyle = "#0c1628"; ctx.beginPath(); ctx.arc(cx, cy, R, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = "rgba(94,231,255,0.3)"; ctx.beginPath(); ctx.arc(cx, cy, R, 0, Math.PI * 2); ctx.stroke(); for (let i = 0; i < 6; i++) { const inc = 0.4 + i * 0.25, rr = R * (1.25 + i * 0.08); ctx.strokeStyle = ["#5ee7ff", "#ffb454", "#7cf3a0", "#b99cff", "#ff5d73", "#e6eef8"][i] + "66"; ctx.beginPath(); ctx.ellipse(cx, cy, rr, rr * Math.abs(Math.cos(inc)), i * 0.5, 0, Math.PI * 2); ctx.stroke(); const a = t * (0.5 + i * 0.1) + i; const x = Math.cos(a) * rr, y = Math.sin(a) * rr * Math.abs(Math.cos(inc)); const rx = x * Math.cos(i * 0.5) - y * Math.sin(i * 0.5), ry = x * Math.sin(i * 0.5) + y * Math.cos(i * 0.5); ctx.fillStyle = ["#5ee7ff", "#ffb454", "#7cf3a0", "#b99cff", "#ff5d73", "#e6eef8"][i]; ctx.beginPath(); ctx.arc(cx + rx, cy + ry, 3, 0, Math.PI * 2); ctx.fill(); } },
  baidu: (ctx, w, h, t, r) => { const hub = [w * 0.6, h * 0.35]; for (let i = 0; i < 12; i++) { const x = r() * w, y = r() * h; ctx.strokeStyle = "rgba(94,231,255,0.3)"; ctx.beginPath(); ctx.moveTo(hub[0], hub[1]); ctx.quadraticCurveTo((hub[0] + x) / 2, Math.min(hub[1], y) - 30, x, y); ctx.stroke(); const s = (t * 0.35 + i * 0.1) % 1; const u = 1 - s; ctx.fillStyle = C.ref; ctx.beginPath(); ctx.arc(u * u * hub[0] + 2 * u * s * ((hub[0] + x) / 2) + s * s * x, u * u * hub[1] + 2 * u * s * (Math.min(hub[1], y) - 30) + s * s * y, 2.5, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = C.live; ctx.beginPath(); ctx.arc(x, y, 3, 0, Math.PI * 2); ctx.fill(); } ctx.fillStyle = C.ref; ctx.beginPath(); ctx.arc(hub[0], hub[1], 6, 0, Math.PI * 2); ctx.fill(); },
  // embodied
  "episode-review": scene3Preview((sc, t) => {
    const phase = (t * 0.4) % 1;
    const grip = phase > 0.35 && phase < 0.8;
    const reach = Math.sin(phase * Math.PI) * 0.6;
    const tcp = armPose(sc, [-1.1, 0.8, 0], 0.5 + phase * 1.2, 0.75 - reach, -1.0 - reach * 0.4, -0.3);
    sc.box([0.1, 0.35, 0], [2.1, 0.7, 1.5], DARK);
    const cube: V3 = grip ? [tcp[0], tcp[1] - 0.18, tcp[2]] : [0.5, 0.84, 0.2];
    sc.box(cube, [0.3, 0.3, 0.3], AMBER);
    sc.box([-0.35, 0.85, -0.5], [0.3, 0.3, 0.3], VIOLET);
    sc.shadow([cube[0], 0, cube[2]], 0.2, 0.2);
  }, { dist: 6.6, pitch: 0.36, target: [0, 1.05, 0], spin: 0.1 }),
  mujoco: scene3Preview((sc, t) => {
    humanoid(sc, t, Math.sin(t * 1.1) > 0.85);
    sc.points.push({ p: [0.2, 0.02, 0.2], color: "#ff5d73", size: 2 }, { p: [-0.2, 0.02, -0.1], color: "#ff5d73", size: 2 });
  }, { dist: 5.6, target: [0, 1.35, 0], spin: 0.18 }),
  "robot-inspector": scene3Preview((sc, t) => {
    const tcp = armPose(sc, [0, 0, 0], t * 0.5, 1.15 + Math.sin(t) * 0.3, -1.3 + Math.cos(t * 0.8) * 0.35, -0.6 + Math.sin(t * 1.3) * 0.3);
    sc.lines.push({ a: tcp, b: [tcp[0] + 0.6, tcp[1], tcp[2]], color: "#ff5d73", width: 1.5 }, { a: tcp, b: [tcp[0], tcp[1] + 0.6, tcp[2]], color: "#7cf3a0", width: 1.5 }, { a: tcp, b: [tcp[0], tcp[1], tcp[2] + 0.6], color: "#5ee7ff", width: 1.5 });
    sc.shadow([0, 0, 0], 0.8, 0.8);
  }, { dist: 5.2, target: [0, 1.15, 0], spin: 0.15 }),
  kinematics: scene3Preview((sc, t) => {
    const tcp = armPose(sc, [-1.0, 0, 0], 0.4 + Math.sin(t * 0.6) * 0.5, 1.1 + Math.sin(t) * 0.4, -1.3 + Math.cos(t) * 0.5, -0.2);
    const goal: V3 = [1.6 + Math.cos(t * 0.7) * 0.5, 1.4 + Math.sin(t * 0.9) * 0.6, Math.sin(t * 0.5) * 0.8];
    sc.box(goal, [0.28, 0.28, 0.28], AMBER);
    sc.lines.push({ a: tcp, b: goal, color: "rgba(255,180,84,0.6)" });
    for (let i = 0; i < 46; i++) { const a = i * 0.7 + t * 0.3; sc.points.push({ p: [-1.2 + Math.cos(a) * (1.6 + (i % 5) * 0.14), 1.1 + Math.sin(a * 1.3) * 1.1, Math.sin(a) * 1.4], color: "rgba(94,231,255,0.35)", size: 1.4 }); }
    sc.shadow([-1.0, 0, 0], 0.55, 0.55);
  }, { dist: 7.2, target: [0.2, 1.4, 0], spin: 0.1 }),
  "policy-monitor": scene3Preview((sc, t, r) => {
    for (let i = 0; i < 9; i++) {
      const gx = (i % 3) - 1, gz = Math.floor(i / 3) - 1;
      const seed = 0.6 + r() * 0.8;
      const th = Math.sin(t * seed + i) * 0.35;
      const cart: V3 = [gx * 2.4 + Math.sin(t * seed * 0.8 + i) * 0.5, 0.22, gz * 2.4];
      sc.box(cart, [0.7, 0.28, 0.5], Math.abs(th) > 0.3 ? [255, 93, 115] : STEEL);
      sc.limb([cart[0], cart[1] + 0.1, cart[2]], [cart[0] + Math.sin(th) * 1.2, cart[1] + Math.cos(th) * 1.2, cart[2]], 0.06, Math.abs(th) > 0.3 ? [255, 93, 115] : CYAN, 5);
      sc.shadow(cart, 0.4, 0.3);
    }
  }, { dist: 9.5, pitch: 0.45, target: [0, 0.5, 0], spin: 0.08 }),
  scenario: (ctx, w, h, t) => { road(ctx, w, h, 2); const s = (t * 0.25) % 1; const ex = w * 0.1 + s * w * 0.6; car(ctx, ex, h * 0.6, 0, C.ref); const ax = ex + 60; const lat = Math.max(0, Math.min(1, (s - 0.35) * 4)); car(ctx, ax, h * 0.4 + lat * h * 0.2, lat * 0.3 * (1 - lat), C.live); ctx.fillStyle = "rgba(255,93,115,0.5)"; ctx.fillRect(ex + 40, h * 0.3, 2, h * 0.4); ctx.fillStyle = C.fg; ctx.font = "9px monospace"; ctx.fillText(`trigger 22 m · gap ${(38 - lat * 20).toFixed(0)} m`, 8, h - 8); for (let i = 0; i < 12; i++) for (let j = 0; j < 8; j++) { const v = Math.sin(i * 0.5 + j * 0.8 + t * 0.5); ctx.fillStyle = v > 0.7 ? C.bad : heat(0.4 + v * 0.3); ctx.fillRect(w - 66 + i * 5, 6 + j * 5, 4, 4); } },
  physics: scene3Preview((sc, t, r) => {
    for (let i = 0; i < 12; i++) {
      const x = (r() - 0.5) * 3, z = (r() - 0.5) * 3;
      const tt = (t * 0.7 + r() * 2) % 2.2;
      const y = Math.max(0.22, 3.2 - 4.9 * tt * tt + (tt > 0.8 ? Math.abs(Math.sin(tt * 6)) * 0.5 : 0));
      sc.box([x, y, z], [0.42, 0.42, 0.42], i % 3 ? CYAN : AMBER, tt + i);
      sc.shadow([x, 0, z], 0.24 + (3 - y) * 0.03, 0.24);
    }
  }, { dist: 7.4, target: [0, 1.1, 0], spin: 0.13 }),
  traffic: (ctx, w, h, t) => { const cx = w * 0.3, cy = h / 2, R = Math.min(w * 0.28, h * 0.4); ctx.strokeStyle = C.line; ctx.lineWidth = 12; ctx.beginPath(); ctx.arc(cx, cy, R, 0, Math.PI * 2); ctx.stroke(); ctx.lineWidth = 1; for (let i = 0; i < 26; i++) { const s = (i / 26) * Math.PI * 2; const jam = Math.sin(s * 3 - t * 0.9); const ang = s + t * (0.6 + 0.25 * jam); ctx.fillStyle = jam > 0.6 ? C.bad : jam > 0.1 ? C.ref : C.live; ctx.save(); ctx.translate(cx + Math.cos(ang) * R, cy + Math.sin(ang) * R); ctx.rotate(ang + Math.PI / 2); ctx.fillRect(-2, -4, 4, 8); ctx.restore(); } for (let y = 0; y < 30; y++) for (let x = 0; x < 20; x++) { const v = Math.sin(x * 0.6 - y * 0.35 + t); ctx.fillStyle = v > 0.6 ? C.bad : v > 0.1 ? C.ref : `rgba(94,231,255,0.5)`; ctx.fillRect(w * 0.62 + x * ((w * 0.35) / 20), 8 + y * ((h - 16) / 30), (w * 0.35) / 20 - 1, (h - 16) / 30 - 1); } },
  "world-model": (ctx, w, h, t) => { const pw = (w - 24) / 3; for (let i = 0; i < 3; i++) { const x = 6 + i * (pw + 6); ctx.fillStyle = "#0e1626"; ctx.fillRect(x, 6, pw, h * 0.55); ctx.fillStyle = "#151c28"; ctx.fillRect(x, h * 0.35, pw, h * 0.26); const drift = i ? Math.sin(t * 0.5) * 8 * i : 0; ctx.fillStyle = "#3d5a80"; ctx.fillRect(x + pw * 0.4 + drift, h * 0.38, pw * 0.25, h * 0.12); if (i) { ctx.fillStyle = C.ref; ctx.fillRect(x + pw * 0.1 + drift * 2, h * 0.42, pw * 0.15, h * 0.08); } ctx.strokeStyle = i ? C.ref : C.live; ctx.strokeRect(x + 0.5, 6.5, pw - 1, h * 0.55 - 1); } plot(ctx, 6, h * 0.66, w - 12, h * 0.3, (u) => u * u * 0.9, C.bad, (t * 0.3) % 1); },
  // annotation
  "lidar-cuboid": (ctx, w, h, t, r) => { for (let i = 0; i < 400; i++) { const x = r() * w, y = h * 0.3 + r() * h * 0.7; ctx.fillStyle = "rgba(58,76,102,0.9)"; ctx.fillRect(x, y, 1.5, 1.5); } const bx = w * 0.45 + Math.sin(t) * 10, by = h * 0.55; const d = Math.min(1, (t % 3) / 1.5); ctx.strokeStyle = C.live; ctx.lineWidth = 1.5; ctx.strokeRect(bx - 22 * d, by - 10 * d, 44 * d, 20 * d); ctx.beginPath(); ctx.moveTo(bx - 22 * d, by - 10 * d); ctx.lineTo(bx - 14 * d, by - 20 * d); ctx.lineTo(bx + 30 * d, by - 20 * d); ctx.lineTo(bx + 22 * d, by - 10 * d); ctx.moveTo(bx + 30 * d, by - 20 * d); ctx.lineTo(bx + 30 * d, by); ctx.lineTo(bx + 22 * d, by + 10 * d); ctx.stroke(); ctx.lineWidth = 1; for (let i = 0; i < 60; i++) { ctx.fillStyle = C.live; ctx.fillRect(bx - 20 + r() * 40, by - 8 + r() * 16, 2, 2); } ctx.strokeStyle = C.ref; ctx.beginPath(); ctx.moveTo(bx, by); ctx.lineTo(bx + 30, by); ctx.moveTo(bx, by); ctx.lineTo(bx, by - 30); ctx.stroke(); ctx.fillStyle = C.fg; ctx.font = "9px monospace"; ctx.fillText("car · IoU 0.82", bx - 20, by - 26); },
  tracking: (ctx, w, h, t, r) => { const frames = 8; for (let k = 0; k < frames; k++) { const x = 16 + k * ((w - 32) / (frames - 1)); const y = h * 0.5 + Math.sin(k * 0.8) * h * 0.2; const key = k === 0 || k === frames - 1 || k === 4; ctx.strokeStyle = key ? C.ref : k > 5 ? C.bad : C.live; ctx.setLineDash(key ? [] : [3, 3]); ctx.strokeRect(x - 10, y - 6, 20, 12); ctx.setLineDash([]); if (key) { ctx.fillStyle = C.ref; ctx.fillRect(x - 2, h - 12, 4, 6); } } ctx.strokeStyle = "rgba(255,180,84,0.5)"; ctx.beginPath(); for (let k = 0; k < frames; k++) { const x = 16 + k * ((w - 32) / (frames - 1)); const y = h * 0.5 + Math.sin(k * 0.8) * h * 0.2; k ? ctx.lineTo(x, y) : ctx.moveTo(x, y); } ctx.stroke(); const cx = 16 + ((t * 30) % (w - 32)); ctx.fillStyle = C.fg; ctx.fillRect(cx - 1, h - 14, 2, 10); void r; },
  image: (ctx, w, h, t) => { ctx.fillStyle = "#0e1626"; ctx.fillRect(0, 0, w, h * 0.55); for (let x = 0; x < w; x += 22) { const bh = h * (0.12 + ((x * 7) % 5) * 0.06); ctx.fillStyle = `hsl(215 30% ${16 + ((x * 3) % 4) * 4}%)`; ctx.fillRect(x, h * 0.55 - bh, 16, bh); } ctx.fillStyle = "#1a2333"; ctx.fillRect(0, h * 0.55, w, h * 0.45); ctx.fillStyle = "#3b4d68"; ctx.fillRect(w * 0.25, h * 0.7, w * 0.16, h * 0.14); ctx.fillStyle = "#4a6b5a"; ctx.fillRect(w * 0.62, h * 0.62, w * 0.22, h * 0.2); const d = Math.min(1, (t % 3) / 1.2); ctx.strokeStyle = C.live; ctx.fillStyle = "rgba(94,231,255,0.2)"; ctx.fillRect(w * 0.24, h * 0.68, w * 0.18 * d, h * 0.18 * d); ctx.strokeRect(w * 0.24, h * 0.68, w * 0.18 * d, h * 0.18 * d); ctx.strokeStyle = C.ref; ctx.beginPath(); ctx.moveTo(w * 0.5, h * 0.55); ctx.quadraticCurveTo(w * 0.42, h * 0.8, w * 0.1, h); ctx.stroke(); for (let i = 0; i < 40; i++) { ctx.fillStyle = "rgba(124,243,160,0.4)"; ctx.fillRect(w * 0.6 + (i % 8) * 6, h * 0.05 + Math.floor(i / 8) * 6, 5, 5); } const mx = w * 0.5 + Math.sin(t) * w * 0.3; ctx.strokeStyle = "rgba(230,238,248,0.3)"; ctx.beginPath(); ctx.moveTo(mx, 0); ctx.lineTo(mx, h); ctx.stroke(); },
  quality: (ctx, w, h, t, r) => { const n = 8; const cell = Math.min((w * 0.5 - 20) / n, (h - 20) / n); for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) { const v = i === j ? 0.6 + r() * 0.4 : Math.abs(i - j) === 1 ? r() * 0.4 : r() * 0.1; ctx.fillStyle = v > 0.05 ? heat(v) : C.panel; ctx.fillRect(10 + j * cell, 10 + i * cell, cell - 1, cell - 1); } for (let i = 0; i < 6; i++) { const y = 12 + i * ((h - 24) / 6); const err = i % 3 === 0; ctx.fillStyle = C.panel; ctx.fillRect(w * 0.55, y, w * 0.42, (h - 24) / 6 - 4); ctx.fillStyle = err ? C.bad : C.ref; ctx.fillRect(w * 0.55, y, 3, (h - 24) / 6 - 4); ctx.fillStyle = C.muted; ctx.font = "8px monospace"; ctx.fillText(["dimension", "attribute", "overlap", "ontology", "ground", "attribute"][i], w * 0.57, y + 10); if ((t * 0.5 + i * 0.3) % 3 < 1.5) { ctx.fillStyle = C.ok; ctx.fillText("✓", w * 0.93, y + 10); } } },
  // dataloop
  pipeline: (ctx, w, h, t, r) => { const n = 7; const gap = (w - 16) / n; const y = h * 0.35; for (let i = 0; i < n; i++) { const x = 8 + i * gap; ctx.fillStyle = C.panel; ctx.strokeStyle = i === 4 && Math.sin(t * 3) > 0 ? C.bad : C.line; ctx.beginPath(); ctx.roundRect(x, y - 10, gap - 6, 20, 4); ctx.fill(); ctx.stroke(); } for (let i = 0; i < 30; i++) { const s = (r() + t * 0.1) % 1; ctx.fillStyle = s > 0.55 && s < 0.7 ? C.ref : C.live; ctx.beginPath(); ctx.arc(8 + s * (w - 16), y + 18 + (i % 4) * 4, 2, 0, Math.PI * 2); ctx.fill(); } for (let i = 0; i < n; i++) { const hh = (1 - i / n) * h * 0.32; ctx.fillStyle = `hsl(${200 + i * 10} 80% 60% / 0.7)`; ctx.fillRect(8 + i * gap, h - 8 - hh, gap - 6, hh); } },
  dataset: (ctx, w, h, t, r) => { const n = 12; for (let i = 0; i < n; i++) { const y = 8 + i * ((h - 16) / n); const v = Math.exp(-i * 0.6) * (0.9 + r() * 0.2); const len = Math.log10(1 + v * 1000) / 3 * (w * 0.6) * Math.min(1, t * 0.6); ctx.fillStyle = i > 6 ? C.ref : C.live; ctx.fillRect(w * 0.3, y, len, (h - 16) / n - 3); ctx.fillStyle = C.muted; ctx.font = "8px monospace"; ctx.fillText(["car", "ped", "truck", "cyclist", "bus", "moto", "cone", "animal", "debris", "emerg.", "stroller", "wheelchair"][i], 6, y + 8); } ctx.fillStyle = C.fg; ctx.font = "9px monospace"; ctx.fillText("long tail →", w * 0.62, h - 10); },
  training: (ctx, w, h, t) => { const n = Math.floor(30 + (t * 20) % 40); plot(ctx, 6, 6, w - 12, h * 0.48, (u) => 1 - Math.min(1, 1.3 * (1 - Math.exp(-u * 4))) + 0.1, C.muted); [C.live, C.ref, C.ok].forEach((c, k) => { ctx.strokeStyle = c; ctx.lineWidth = 1.5; ctx.beginPath(); for (let i = 0; i <= 60; i++) { const u = i / 60; const v = 0.15 + Math.exp(-u * (3 + k)) * 0.8 + (k === 1 && u > 0.55 ? (u - 0.55) * 0.8 : 0); const px = 10 + u * (w - 20), py = 6 + h * 0.48 - 4 - Math.min(1, v) * (h * 0.48 - 8); i ? ctx.lineTo(px, py) : ctx.moveTo(px, py); } ctx.stroke(); }); ctx.lineWidth = 1; ctx.strokeStyle = C.bad; ctx.setLineDash([3, 3]); ctx.beginPath(); ctx.moveTo(10 + 0.6 * (w - 20), 8); ctx.lineTo(10 + 0.6 * (w - 20), h * 0.5); ctx.stroke(); ctx.setLineDash([]); plot(ctx, 6, h * 0.56, w - 12, h * 0.4, (u) => Math.min(1, u * 1.4) * 0.9, C.ok, (n / 70) % 1); },
  // spatial / ai / markets / science / industry
  viewer: scene3Preview((sc, t, r) => {
    for (let i = 0; i < 1100; i++) {
      const u = r(), v = r(); const th = u * Math.PI * 2, ph = Math.acos(2 * v - 1);
      const shape = i % 5;
      const R = shape === 0 ? 1.9 : 1.15;
      const p: V3 = shape === 0
        ? [Math.cos(th) * R, 0.05 + r() * 0.06, Math.sin(th) * R * (0.6 + r() * 0.5)]
        : [Math.sin(ph) * Math.cos(th) * R, 1.35 + Math.cos(ph) * R * 0.8, Math.sin(ph) * Math.sin(th) * R];
      sc.points.push({ p, color: shape === 0 ? "rgba(58,76,102,0.9)" : shape === 1 ? "rgba(255,180,84,0.75)" : "rgba(94,231,255,0.8)", size: 1.6 });
    }
    void t;
  }, { dist: 6.4, target: [0, 1.2, 0], spin: 0.22 }),
  "inside-models": (ctx, w, h, t) => { const m = 8; const cell = Math.min((w * 0.32) / m, (h * 0.7) / m); for (let i = 0; i < m; i++) for (let j = 0; j < m; j++) { const v = j <= i ? Math.exp(-Math.abs(i - j) * 0.6) * (0.6 + 0.4 * Math.sin(t + i * 0.7 - j)) : 0; ctx.fillStyle = v > 0.02 ? heat(Math.min(1, v)) : "rgba(13,20,32,0.9)"; ctx.fillRect(w - 8 - (m - j) * cell, 8 + i * cell, cell - 1, cell - 1); } const n = 9; const xs = Array.from({ length: n }, (_, i) => 12 + (i / (n - 1)) * (w * 0.6)); const y = h * 0.72; for (let i = 0; i < n; i++) for (let j = 0; j < i; j++) { const a = 0.5 + 0.5 * Math.sin(t * 1.3 + i * 0.7 - j * 1.1); if (a < 0.55) continue; ctx.strokeStyle = `rgba(94,231,255,${(a - 0.5) * 1.6})`; ctx.lineWidth = 1 + (a - 0.5) * 3; ctx.beginPath(); ctx.moveTo(xs[i], y); ctx.quadraticCurveTo((xs[i] + xs[j]) / 2, y - (xs[i] - xs[j]) * 0.8, xs[j], y); ctx.stroke(); } ctx.lineWidth = 1; const toks = ["the", "robot", "picked", "the", "red", "cube", "it", "was", "near"]; xs.forEach((x, i) => { const on = i === Math.floor(t * 1.5) % n; ctx.fillStyle = on ? C.ref : C.fg; ctx.beginPath(); ctx.arc(x, y, 4, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = on ? C.ref : C.muted; ctx.font = "8px monospace"; ctx.save(); ctx.translate(x, y + 10); ctx.rotate(0.6); ctx.fillText(toks[i], 0, 0); ctx.restore(); }); },
  microstructure: (ctx, w, h, t, r) => { const mid = w / 2; for (let i = 0; i < 24; i++) { const d = i / 24; const bh = (0.2 + d * 0.8) * h * 0.7 * (0.9 + 0.1 * Math.sin(t * 4 + i)); ctx.fillStyle = "rgba(124,243,160,0.7)"; ctx.fillRect(mid - 4 - i * 6, h - 8 - bh, 5, bh); ctx.fillStyle = "rgba(255,93,115,0.7)"; const b2 = bh * (0.85 + 0.15 * r()); ctx.fillRect(mid + 1 + i * 6, h - 8 - b2, 5, b2); } let px = 8, py = h * 0.35; ctx.strokeStyle = C.ref; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.moveTo(px, py); for (let i = 1; i < 40; i++) { px = 8 + (i / 39) * (w - 16); py += (r() - 0.5) * 10 + Math.sin(t + i * 0.3) * 1.5; ctx.lineTo(px, py); } ctx.stroke(); ctx.lineWidth = 1; },
  dynamics: (ctx, w, h, t) => { let x = 0.1, y = 0, z = 0; const dt = 0.01, N = 1800, skip = Math.floor(t * 40) % 400; const cx = w / 2, cy = h * 0.95; ctx.beginPath(); for (let i = 0; i < N + skip; i++) { const dx = 10 * (y - x), dy = x * (28 - z) - y, dz = x * y - (8 / 3) * z; x += dx * dt; y += dy * dt; z += dz * dt; if (i < skip) continue; const px = cx + x * (w / 60), py = cy - z * (h / 55); ctx.strokeStyle = `hsl(${190 + ((i - skip) / N) * 120} 90% 65% / 0.8)`; if (i === skip) ctx.moveTo(px, py); else { ctx.lineTo(px, py); ctx.stroke(); ctx.beginPath(); ctx.moveTo(px, py); } } },
  networks: (ctx, w, h, t, r) => { const nodes = [[0.1, 0.5], [0.3, 0.2], [0.3, 0.8], [0.55, 0.35], [0.55, 0.65], [0.8, 0.2], [0.8, 0.8], [0.93, 0.5]]; const edges = [[0, 1], [0, 2], [1, 3], [2, 4], [3, 5], [4, 6], [5, 7], [6, 7], [3, 4], [1, 2]]; edges.forEach(([a, b], i) => { const [ax, ay] = nodes[a], [bx, by] = nodes[b]; const load = 0.4 + 0.6 * Math.abs(Math.sin(t * 0.7 + i)); ctx.strokeStyle = load > 0.9 ? C.bad : load > 0.7 ? C.ref : "#27394f"; ctx.lineWidth = 1 + load * 3; ctx.beginPath(); ctx.moveTo(ax * w, ay * h); ctx.lineTo(bx * w, by * h); ctx.stroke(); for (let k = 0; k < 3; k++) { const s = (t * 0.4 * load + k / 3 + r() * 0.01) % 1; ctx.fillStyle = C.live; ctx.beginPath(); ctx.arc(ax * w + (bx - ax) * w * s, ay * h + (by - ay) * h * s, 2, 0, Math.PI * 2); ctx.fill(); } }); ctx.lineWidth = 1; nodes.forEach(([x, y], i) => { ctx.fillStyle = i === 0 || i === 7 ? C.ok : C.ref; ctx.beginPath(); ctx.arc(x * w, y * h, i === 0 || i === 7 ? 7 : 5, 0, Math.PI * 2); ctx.fill(); }); },
};
