import { c, lib, type SceneDef } from "../types";

const clsSel = { key: "cls", label: "Class", type: "select" as const, options: [{ value: "car", label: "Car" }, { value: "pedestrian", label: "Pedestrian" }, { value: "cyclist", label: "Cyclist" }], default: "car" };

export const annotation: SceneDef[] = [
  {
    id: "lidar-cuboid", domain: "annotation", title: "LiDAR cuboid labeling", question: "How fast can a person draw an accurate 3D box, and how much can the tool do for them?", input: "Synthetic LiDAR frame with ground-truth objects", output: "Cuboids with class, pose and size; IoU against ground truth",
    demos: [
      { id: "cuboid", title: "Cuboid tool", summary: "Click a point to place a class-sized box, then move / rotate / scale it with a gizmo (keys g / e / s, Delete removes). Top, front and side orthographic insets follow the selection.", controls: [clsSel, { key: "insets", label: "Ortho insets", type: "toggle", default: true }, { key: "mode_t", label: "Move (g)", type: "action" }, { key: "mode_r", label: "Rotate (e)", type: "action" }, { key: "mode_s", label: "Scale (s)", type: "action" }, { key: "remove", label: "Delete selected", type: "action" }],
        legend: [{ color: c.live, label: "Car box" }, { color: c.bad, label: "Pedestrian box" }, { color: c.ok, label: "Cyclist box" }],
        assumptions: "Ground truth is the synthetic scene generator; IoU uses an axis-aligned BEV approximation. Real tools add snapping, height-from-ground and AI pre-labels.", camera: "Click a point to add a box · drag gizmo · g/e/s modes", libs: [lib.three, lib.transform, lib.xtreme1], load: () => import("../engines/annotation/CuboidTool") },
      { id: "oneclick", title: "One-click box", summary: "Click any object point: a region-growing cluster above the ground plane is extracted with a spatial hash and an oriented box is fitted by principal direction (LATTE-style one-click annotation).", controls: [{ key: "radius", label: "Grow radius", type: "range", min: 0.2, max: 1.2, step: 0.05, unit: "m", default: 0.5 }, { key: "ground", label: "Ground cut height", type: "range", min: 0, max: 0.6, step: 0.05, unit: "m", default: 0.15 }],
        legend: [{ color: c.live, label: "Cluster → car" }, { color: c.bad, label: "Cluster → pedestrian" }, { color: c.ok, label: "Cluster → cyclist" }],
        assumptions: "Class is guessed from fitted dimensions. Clustering fails when objects touch; production tools use learned segmentation (SAM-style) instead.", camera: "Click an object", libs: [lib.three, lib.xtreme1], load: () => import("../engines/annotation/OneClick") },
      { id: "projection", title: "Camera projection check", summary: "3D labels are projected into a synthetic front camera; nudge one label and watch the reprojection error against the image silhouette.", controls: [{ key: "edit", label: "Label to edit", type: "range", min: 0, max: 6, step: 1, default: 0 }, { key: "dx", label: "Δ x", type: "range", min: -1.5, max: 1.5, step: 0.05, unit: "m", default: 0.4 }, { key: "dz", label: "Δ z", type: "range", min: -1.5, max: 1.5, step: 0.05, unit: "m", default: 0 }, { key: "dyaw", label: "Δ yaw", type: "range", min: -30, max: 30, step: 1, unit: "°", default: 8 }, { key: "fov", label: "Camera FOV", type: "range", min: 40, max: 90, step: 1, unit: "°", default: 60 }],
        legend: [{ color: c.ref, label: "Label under edit" }, { color: c.muted, label: "Image silhouette (GT)" }, { color: c.live, label: "Other labels" }],
        assumptions: "Pinhole projection of the exact box corners; the image is drawn from ground truth. Real fusion tools also render the LiDAR points into the image.", libs: [lib.three, lib.canvas, lib.xtreme1], load: () => import("../engines/annotation/ProjectionCheck") },
    ],
  },
  {
    id: "tracking", domain: "annotation", title: "Tracking & propagation", question: "How many frames must a human actually label when boxes can be propagated, associated and locked?", input: "40-frame synthetic sequence with moving and parked objects", output: "Interpolated boxes, track ids, lock decisions, IoU per frame",
    demos: [
      { id: "keyframes", title: "Keyframe interpolation", summary: "Boxes exist only at keyframes; every other frame is interpolated (linear pose, shortest-arc yaw). Add keyframes where the interpolation turns red to fix the curved car.", controls: [{ key: "rate", label: "Playback rate", type: "range", min: 0.25, max: 3, step: 0.25, unit: "×", default: 1 }, { key: "trails", label: "Show interpolated trails", type: "toggle", default: true }, { key: "addKey", label: "Add keyframe here", type: "action", hint: "Marks the current frame as labeled" }, { key: "clearKeys", label: "Reset keyframes", type: "action" }],
        legend: [{ color: c.live, label: "IoU > 0.5" }, { color: c.bad, label: "IoU ≤ 0.5 — needs a keyframe" }, { color: c.ref, label: "Keyframe / trail" }],
        assumptions: "Keyframe poses are taken from ground truth (a perfect human). Interpolation is linear; tools often use constant-velocity or spline models.", camera: "Drag the timeline · add keyframes", libs: [lib.three, lib.xtreme1, lib.cvat], load: () => import("../engines/annotation/Tracking") },
      { id: "association", title: "ID association", summary: "Noisy per-frame detections are matched to tracks by gated nearest-neighbour with velocity prediction; ID switches and fragments are counted against ground truth.", controls: [{ key: "gate", label: "Gating radius", type: "range", min: 0.5, max: 6, step: 0.1, unit: "m", default: 2.5 }, { key: "noise", label: "Detection noise", type: "range", min: 0, max: 2, step: 0.1, unit: "m", default: 0.4 }, { key: "drop", label: "Dropout rate", type: "range", min: 0, max: 0.6, step: 0.05, default: 0.1 }, { key: "alpha", label: "Velocity update α", type: "range", min: 0, max: 1, step: 0.05, default: 0.3 }, { key: "maxMiss", label: "Max miss time", type: "range", min: 0.1, max: 2, step: 0.1, unit: "s", default: 0.6 }],
        legend: [{ color: c.live, label: "Detection" }, { color: c.muted, label: "GT box" }, { color: c.ref, label: "Ego" }],
        assumptions: "Greedy matching, not Hungarian; constant-velocity prediction, no Kalman covariance. Enough to see how gating and dropout trade ID switches for fragments.", camera: "Bird's-eye view", libs: [lib.canvas], load: () => import("../engines/annotation/Association") },
      { id: "staticlock", title: "Static lock", summary: "Objects whose motion is below a threshold are locked to a single world-frame box for the whole sequence and their points are accumulated across frames — one label instead of forty.", controls: [{ key: "rate", label: "Playback rate", type: "range", min: 0.25, max: 3, step: 0.25, unit: "×", default: 1 }, { key: "threshold", label: "Lock threshold", type: "range", min: 0.05, max: 3, step: 0.05, unit: "m/s", default: 0.3 }, { key: "accumulate", label: "Accumulate locked points", type: "toggle", default: true }],
        legend: [{ color: c.ok, label: "Locked (one label)" }, { color: c.ref, label: "Per-frame" }, { color: c.ok, label: "Accumulated points" }],
        assumptions: "Motion is measured from first to last frame of ground truth; ego is stationary. With a moving ego, locking needs ego-pose compensation first.", libs: [lib.three], load: () => import("../engines/annotation/StaticLock") },
    ],
  },
  {
    id: "image", domain: "annotation", title: "Image tools", question: "Boxes, polygons, lane curves and masks — the four primitives every image labeling tool needs.", input: "Synthetic street image (1280×720)", output: "Shapes, Bézier lanes, class masks; IoU and pixel error",
    demos: [
      { id: "boxes", title: "Box & polygon", summary: "Drag to draw a box, click to add polygon vertices (double-click closes). Boxes are scored against hidden ground truth; toggle it to compare.", controls: [{ key: "tool", label: "Tool", type: "select", options: [{ value: "box", label: "Bounding box" }, { value: "poly", label: "Polygon" }], default: "box" }, { key: "cls", label: "Class", type: "select", options: [{ value: "car", label: "Car" }, { value: "pedestrian", label: "Pedestrian" }, { value: "sign", label: "Sign" }, { value: "other", label: "Other" }], default: "car" }, { key: "showGt", label: "Show ground truth", type: "toggle", default: false }, { key: "undo", label: "Undo (⌘Z)", type: "action" }, { key: "clear", label: "Clear all", type: "action" }],
        legend: [{ color: c.live, label: "Car" }, { color: c.bad, label: "Pedestrian" }, { color: c.ref, label: "Sign" }, { color: c.violet, label: "Other" }],
        assumptions: "Pixel coordinates in the 1280×720 image space regardless of display size. No zoom/pan; production tools add both plus edge snapping.", camera: "Drag / click on the image", libs: [lib.canvas, lib.cvat], load: () => import("../engines/annotation/ImageBoxes") },
      { id: "lanes", title: "Lane curves", summary: "Each lane is a cubic Bézier with draggable control points; the sampled curve is compared with the painted line and the mean pixel error is reported per lane.", controls: [{ key: "samples", label: "Samples per lane", type: "range", min: 8, max: 64, step: 4, default: 24 }, { key: "handles", label: "Show handles", type: "toggle", default: true }, { key: "samplesDots", label: "Show samples", type: "toggle", default: false }],
        legend: [{ color: c.live, label: "Lane 1" }, { color: c.ref, label: "Lane 2 (center)" }, { color: c.ok, label: "Lane 3" }],
        assumptions: "Image-space curves only; real lane labels live in BEV/3D and are projected. Error is nearest-sample distance to the painted polyline.", camera: "Drag control points", libs: [lib.canvas], load: () => import("../engines/annotation/LaneCurves") },
      { id: "mask", title: "Segmentation brush", summary: "Paint class masks on a 4 px label grid with a round brush and eraser; per-class coverage updates live. A one-click sky fill shows how rules speed up dense labeling.", controls: [{ key: "cls", label: "Class", type: "select", options: ["road", "car", "pedestrian", "building", "sky"].map((v) => ({ value: v, label: v })), default: "road" }, { key: "radius", label: "Brush radius", type: "range", min: 6, max: 80, step: 2, unit: "px", default: 28 }, { key: "opacity", label: "Mask opacity", type: "range", min: 0.2, max: 1, step: 0.05, default: 0.55 }, { key: "eraser", label: "Eraser", type: "toggle", default: false }, { key: "fillSky", label: "Fill sky above horizon", type: "action" }, { key: "clear", label: "Clear mask", type: "action" }],
        legend: [{ color: c.live, label: "road" }, { color: c.violet, label: "car" }, { color: c.bad, label: "pedestrian" }, { color: c.ref, label: "building" }, { color: c.ok, label: "sky" }],
        assumptions: "Label grid is 320×180 (4 px cells) to keep painting cheap; export would upsample. No superpixel or model-assisted fill.", camera: "Paint on the image", libs: [lib.canvas, lib.cvat], load: () => import("../engines/annotation/SegBrush") },
    ],
  },
  {
    id: "quality", domain: "annotation", title: "Quality control & export", question: "Do two annotators agree, do the labels obey the ontology, and can they leave in a standard format?", input: "Label sets from two annotators, ontology rules", output: "IoU matrix, rule violations with fixes, KITTI / nuScenes / CSV files",
    demos: [
      { id: "consensus", title: "Inter-annotator IoU", summary: "Two annotators label the same scene with different noise and misses; the pairwise IoU matrix, unmatched labels and class mismatches drive an agreement rate.", controls: [{ key: "noiseA", label: "Annotator A noise", type: "range", min: 0, max: 2, step: 0.1, unit: "m", default: 0.3 }, { key: "noiseB", label: "Annotator B noise", type: "range", min: 0, max: 2, step: 0.1, unit: "m", default: 0.8 }, { key: "missB", label: "Annotator B miss rate", type: "range", min: 0, max: 0.5, step: 0.05, default: 0.15 }, { key: "thr", label: "Match IoU threshold", type: "range", min: 0.2, max: 0.9, step: 0.05, default: 0.5 }],
        legend: [{ color: c.live, label: "A · matched" }, { color: c.bad, label: "A · unmatched" }, { color: c.ref, label: "B (dashed)" }],
        assumptions: "IoU is an axis-aligned BEV × height approximation. Agreement is per-label, not per-pixel; real QC also samples a gold set.", camera: "Bird's-eye view + matrix", libs: [lib.canvas], load: () => import("../engines/annotation/Consensus") },
      { id: "validation", title: "Ontology validation", summary: "Every label is checked against class dimension ranges, required attributes, ground contact and overlap; violations list a one-click fix and the pass rate updates.", controls: [{ key: "strict", label: "Missing attribute is an error", type: "toggle", default: true }, { key: "groundTol", label: "Ground tolerance", type: "range", min: 0, max: 1, step: 0.05, unit: "m", default: 0.3 }],
        legend: [{ color: c.bad, label: "Error" }, { color: c.ref, label: "Warning" }, { color: c.ok, label: "Pass" }],
        assumptions: "Rules are hard-coded for three classes. Applying a fix only marks the issue resolved in this demo; a real tool would edit the label.", camera: "List view", libs: [lib.xtreme1], load: () => import("../engines/annotation/Validation") },
      { id: "export", title: "Export formats", summary: "The same labels serialized to KITTI label lines, a nuScenes-style sample_annotation JSON, or a flat CSV — preview and download.", controls: [{ key: "format", label: "Format", type: "select", options: [{ value: "kitti", label: "KITTI (.txt)" }, { value: "nuscenes", label: "nuScenes (.json)" }, { value: "csv", label: "CSV" }], default: "nuscenes" }, { key: "download", label: "Download file", type: "action" }],
        legend: [{ color: c.live, label: "Serialized labels" }],
        assumptions: "KITTI expects camera-frame coordinates; the conversion here is a simple axis swap without a real calibration file. nuScenes tokens are placeholders.", camera: "Text preview", libs: [lib.kitti, lib.nuscenes], load: () => import("../engines/annotation/Export") },
    ],
  },
];
