import { c, lib, type SceneDef } from "../types";

export const driving: SceneDef[] = [
  {
    id: "perception", domain: "driving", title: "Perception", question: "What does the vehicle see — as returns, as a bird's-eye grid, as voxels, and through six cameras at once?", input: "Synthetic sweep, actor list, sensor rate", output: "Point cloud, BEV occupancy, voxel grid, projected boxes",
    demos: [
      { id: "lidar", title: "LiDAR sweep + BEV", summary: "Ray-cast LiDAR sweep against a synthetic city, ground segmentation, jittered 3D detections and a bird's-eye occupancy inset.", controls: [
        { key: "beams", label: "Laser channels", type: "range", min: 16, max: 128, step: 16, default: 64 }, { key: "rate", label: "Sweep rate", type: "range", min: 5, max: 20, step: 1, unit: "Hz", default: 10 }, { key: "actors", label: "Traffic actors", type: "range", min: 0, max: 12, step: 1, default: 6 }, { key: "noise", label: "Range noise", type: "range", min: 0, max: 0.3, step: 0.01, unit: "m", default: 0.03 }, { key: "ground", label: "Ground segmentation", type: "toggle", default: true }, { key: "boxes", label: "3D detections", type: "toggle", default: true } ],
        legend: [{ color: c.live, label: "Obstacle returns" }, { color: c.muted, label: "Ground" }, { color: c.ok, label: "Tracked box" }, { color: c.ref, label: "Ego vehicle" }],
        assumptions: "Synthetic urban scene ray-cast against boxes and a flat ground plane. Detections are ground-truth actors with jitter, not a trained network. The BEV inset rasterizes returns into a 0.5 m occupancy grid.", libs: [lib.three, lib.canvas], load: () => import("../engines/driving/Lidar") },
      { id: "occupancy", title: "Occupancy voxels", summary: "Semantic occupancy grid (0.8 m voxels) around the ego with class filter, height slice and per-voxel flow arrows for moving classes.", controls: [
        { key: "range", label: "Sensing range", type: "range", min: 10, max: 30, step: 1, unit: "m", default: 24 }, { key: "slice", label: "Height slice", type: "range", min: 0.8, max: 6.4, step: 0.8, unit: "m", default: 6.4 }, { key: "egoSpeed", label: "Ego speed", type: "range", min: 0, max: 15, step: 0.5, unit: "m/s", default: 6 }, { key: "classes", label: "Show class", type: "select", options: [{ value: "all", label: "All classes" }, { value: "road", label: "Road" }, { value: "building", label: "Building" }, { value: "vehicle", label: "Vehicle" }, { value: "pedestrian", label: "Pedestrian" }, { value: "vegetation", label: "Vegetation" }], default: "all" }, { key: "flow", label: "Flow arrows", type: "toggle", default: true } ],
        legend: [{ color: "#27394f", label: "Road" }, { color: c.muted, label: "Building" }, { color: c.live, label: "Vehicle" }, { color: c.bad, label: "Pedestrian" }, { color: c.ok, label: "Vegetation" }, { color: c.ref, label: "Flow" }],
        assumptions: "Voxels are classified from ground-truth geometry, not predicted by a network. Flow arrows show the actor's true velocity. Real occupancy networks predict all of this from cameras.", libs: [lib.three], load: () => import("../engines/driving/Occupancy") },
      { id: "surround", title: "Six-camera surround", summary: "The same scene rendered through six synthetic cameras with scissor viewports; 3D boxes are projected into each image via the camera matrices.", controls: [
        { key: "egoSpeed", label: "Ego speed", type: "range", min: 0, max: 15, step: 0.5, unit: "m/s", default: 5 }, { key: "fovScale", label: "FOV scale", type: "range", min: 0.7, max: 1.4, step: 0.05, default: 1 }, { key: "mount", label: "Camera offset", type: "range", min: 0, max: 2.5, step: 0.1, unit: "m", default: 1.2 }, { key: "range", label: "Box range", type: "range", min: 10, max: 60, step: 1, unit: "m", default: 40 }, { key: "boxes", label: "Project 3D boxes", type: "toggle", default: true } ],
        legend: [{ color: c.ok, label: "Vehicle box" }, { color: c.bad, label: "Pedestrian box" }, { color: c.live, label: "Viewport" }],
        assumptions: "Pinhole cameras without distortion; box projection uses the exact camera matrices (world → view → clip). Real rigs need intrinsics, distortion and rolling-shutter models.", camera: "Fixed six-camera rig", libs: [lib.three, lib.canvas], load: () => import("../engines/driving/Surround") },
    ],
  },
  {
    id: "planning", domain: "driving", title: "Planning & prediction", question: "Which trajectory did the planner pick, how far does a late brake travel, and what does prediction think the others will do?", input: "Speed, gap, comfort weight, horizon", output: "Ranked trajectories, stopping distance, multimodal hypotheses",
    demos: [
      { id: "planner", title: "Lattice planner", summary: "Frenet-frame lattice sampling over a 4 s horizon on a cut-in scenario; every candidate is scored and the winner is shown with TTC.", controls: [
        { key: "speed", label: "Ego speed", type: "range", min: 20, max: 110, step: 1, unit: "km/h", default: 70 }, { key: "gap", label: "Cut-in gap", type: "range", min: 8, max: 60, step: 1, unit: "m", default: 22 }, { key: "cutSpeed", label: "Cut-in vehicle speed", type: "range", min: 20, max: 100, step: 1, unit: "km/h", default: 55 }, { key: "comfort", label: "Comfort weight", type: "range", min: 0, max: 1, step: 0.05, default: 0.5 }, { key: "candidates", label: "Show all candidates", type: "toggle", default: true } ],
        legend: [{ color: c.ok, label: "Selected trajectory" }, { color: c.muted, label: "Rejected candidate" }, { color: c.bad, label: "Collision risk" }, { color: c.ref, label: "Cut-in vehicle" }],
        assumptions: "Lattice planner samples lateral offsets × target speeds over a 4 s horizon in a Frenet frame along a straight road. Cost = collision + jerk + deviation. Actors follow constant-velocity prediction.", libs: [lib.three], load: () => import("../engines/driving/Planner") },
      { id: "braking", title: "Braking distance", summary: "Analytic stopping distance for two reaction delays side by side, with impact speed if the obstacle is closer than the stopping distance.", controls: [
        { key: "speed", label: "Initial speed", type: "range", min: 10, max: 120, step: 1, unit: "km/h", default: 60 }, { key: "distance", label: "Obstacle distance", type: "range", min: 10, max: 120, step: 1, unit: "m", default: 40 }, { key: "delay", label: "Reaction delay", type: "range", min: 0, max: 2, step: 0.05, unit: "s", default: 0.5 }, { key: "friction", label: "Friction μ", type: "range", min: 0.2, max: 1, step: 0.05, default: 0.7 } ],
        legend: [{ color: c.live, label: "Current setup" }, { color: c.ref, label: "Brakes 0.8 s later" }, { color: c.bad, label: "Obstacle" }],
        assumptions: "Stopping distance = v·t_delay + v²/(2μg). No slope, tyre temperature, sensor latency or full AEB logic. Not for real-world driving judgement.", libs: [lib.three], load: () => import("../engines/driving/Braking") },
      { id: "prediction", title: "Multimodal prediction", summary: "Every agent at an intersection gets K maneuver hypotheses with softmax probabilities; the fan fades with probability and TTC to the ego is tracked.", controls: [
        { key: "horizon", label: "Horizon", type: "range", min: 2, max: 8, step: 0.5, unit: "s", default: 5 }, { key: "temperature", label: "Softmax temperature", type: "range", min: 0.3, max: 3, step: 0.1, default: 1 }, { key: "topK", label: "Top-K shown", type: "range", min: 1, max: 6, step: 1, default: 3 }, { key: "showAll", label: "Show all hypotheses", type: "toggle", default: false } ],
        legend: [{ color: c.ok, label: "Most likely" }, { color: c.live, label: "2nd" }, { color: c.violet, label: "Other" }, { color: c.ref, label: "Ego" }, { color: c.bad, label: "Pedestrian" }],
        assumptions: "Hypotheses are hand-written maneuver priors reweighted by distance to the intersection, not a learned model. Real predictors output trajectories and probabilities jointly from map and history.", libs: [lib.three], load: () => import("../engines/driving/Prediction") },
    ],
  },
  {
    id: "log-replay", domain: "driving", title: "Log replay (MCAP)", question: "Can I scrub a drive log and see point cloud, pose, state and signals at the same instant?", input: "MCAP (json-encoded channels) — built-in synthetic drive or your own file", output: "Synchronized 3D replay, state swimlanes, multi-panel plots",
    demos: [
      { id: "mcap", title: "MCAP 3D replay", summary: "A 30 s drive is written as a real MCAP file with @mcap/core (chunked, indexed), read back with McapIndexedReader, and replayed: point cloud, ego pose, trail and topic list with a scrubber.", controls: [
        { key: "rate", label: "Playback rate", type: "range", min: 0.25, max: 4, step: 0.25, unit: "×", default: 1 }, { key: "follow", label: "Follow ego", type: "toggle", default: true }, { key: "loop", label: "Loop", type: "toggle", default: true }, { key: "file", label: "Open .mcap", type: "file", accept: ".mcap", hint: "json-encoded channels are decoded; /tf/ego {x,y,yaw} and /lidar/points {points:[x,y,z…]} drive the 3D view" } ],
        legend: [{ color: c.live, label: "Point cloud (height)" }, { color: c.ref, label: "Ego" }, { color: "#27394f", label: "Ground returns" }],
        assumptions: "Messages are json-encoded with jsonschema schemas; protobuf/ROS2 CDR decoding is not included. The reader loads the whole file in memory — fine for demos, not for multi-GB logs.", libs: [lib.mcap, lib.foxglove, lib.three, lib.foxgloveApp], load: () => import("../engines/driving/McapReplay") },
      { id: "states", title: "State transitions", summary: "Swimlane timeline of /planner/state, brake-event detection over a threshold, and speed/steer plots synchronized to the same cursor.", controls: [
        { key: "rate", label: "Playback rate", type: "range", min: 0.25, max: 4, step: 0.25, unit: "×", default: 1 }, { key: "brakeThreshold", label: "Brake event threshold", type: "range", min: 0.05, max: 0.9, step: 0.05, default: 0.3 }, { key: "file", label: "Open .mcap", type: "file", accept: ".mcap", hint: "uses /planner/state {state}, /vehicle/brake, /vehicle/speed, /vehicle/steer" } ],
        legend: [{ color: c.live, label: "LANE_FOLLOW" }, { color: c.violet, label: "PREPARE" }, { color: c.ok, label: "LANE_CHANGE" }, { color: c.ref, label: "YIELD" }, { color: c.bad, label: "STOP / brake" }],
        assumptions: "State segments are drawn from message time to the next message; event detection is a simple rising-edge threshold.", camera: "Click or drag the timeline to seek", libs: [lib.mcap, lib.canvas, lib.foxgloveApp], load: () => import("../engines/driving/StateTimeline") },
      { id: "plots", title: "Multi-panel plots", summary: "Every numeric channel becomes a panel with a shared playback cursor and hover readout; a derived acceleration signal is computed from speed with a smoothing window.", controls: [
        { key: "rate", label: "Playback rate", type: "range", min: 0.25, max: 4, step: 0.25, unit: "×", default: 1 }, { key: "derived", label: "Derived acceleration panel", type: "toggle", default: true }, { key: "smooth", label: "Smoothing window", type: "range", min: 1, max: 40, step: 1, unit: "samples", default: 8 }, { key: "file", label: "Open .mcap", type: "file", accept: ".mcap", hint: "any json-encoded numeric fields become panels" } ],
        legend: [{ color: c.live, label: "Field 1" }, { color: c.ref, label: "Field 2" }, { color: c.ok, label: "Field 3" }, { color: c.violet, label: "Derived" }],
        assumptions: "Panels use message index as x; irregular sample rates are not resampled. Derivative uses the true timestamps.", camera: "Hover for readouts · drag timeline to seek", libs: [lib.mcap, lib.canvas, lib.uplot], load: () => import("../engines/driving/PlotPanels") },
    ],
  },
  {
    id: "calibration", domain: "driving", title: "Sensor calibration", question: "Is the LiDAR aligned with the camera in space and in time — and by how much is it off?", input: "Synthetic LiDAR returns, synthetic camera image, extrinsics, timestamps", output: "Projection overlay, residual heatmap, estimated offsets",
    demos: [
      { id: "projection", title: "Projection & extrinsics", summary: "LiDAR points projected into a synthetic camera image through editable extrinsics (6 DoF); the checkerboard wall and poles make misalignment obvious.", controls: [
        { key: "dyaw", label: "Δ yaw", type: "range", min: -5, max: 5, step: 0.1, unit: "°", default: 1.5 }, { key: "dpitch", label: "Δ pitch", type: "range", min: -5, max: 5, step: 0.1, unit: "°", default: 0 }, { key: "droll", label: "Δ roll", type: "range", min: -5, max: 5, step: 0.1, unit: "°", default: 0 }, { key: "dx", label: "Δ x", type: "range", min: -0.5, max: 0.5, step: 0.01, unit: "m", default: 0 }, { key: "dy", label: "Δ y", type: "range", min: -0.5, max: 0.5, step: 0.01, unit: "m", default: 0.1 }, { key: "dz", label: "Δ z", type: "range", min: -0.5, max: 0.5, step: 0.01, unit: "m", default: 0 }, { key: "focal", label: "Focal length", type: "range", min: 600, max: 1600, step: 10, unit: "px", default: 1040 }, { key: "pointSize", label: "Point size", type: "range", min: 1, max: 5, step: 0.5, unit: "px", default: 2 }, { key: "colorBy", label: "Color by", type: "select", options: [{ value: "depth", label: "Depth" }, { value: "height", label: "Height" }], default: "depth" } ],
        legend: [{ color: c.live, label: "Near / high" }, { color: c.ref, label: "Mid" }, { color: c.bad, label: "Far / low" }],
        assumptions: "Pinhole camera, no lens distortion, LiDAR→camera as Euler XYZ. The image is drawn analytically from the true extrinsics; your Δ values are added on top.", camera: "Move the Δ sliders to break and restore alignment", libs: [lib.three, lib.canvas], load: () => import("../engines/driving/CalibProjection") },
      { id: "residual", title: "Residual heatmap + refine", summary: "Edge points are projected and scored by distance to image edges; the per-cell heatmap shows where the error concentrates and a coordinate-descent refine walks the extrinsics back.", controls: [
        { key: "auto", label: "Auto-refine while playing", type: "toggle", default: true }, { key: "gridCells", label: "Heatmap cells", type: "range", min: 4, max: 16, step: 1, default: 10 }, { key: "refine", label: "Restart refinement", type: "action", hint: "Starts from the mis-calibrated guess again" } ],
        legend: [{ color: "#0c1628", label: "0 px" }, { color: c.live, label: "~4 px" }, { color: c.ref, label: "~8 px" }, { color: c.bad, label: "12+ px" }],
        assumptions: "Edge distance is analytic (checker and pole edges), not a real Canny map. Refinement is greedy coordinate descent, not Levenberg–Marquardt.", libs: [lib.three, lib.canvas], load: () => import("../engines/driving/CalibResidual") },
      { id: "timeoffset", title: "Time offset", summary: "The lateral position of a passing car from LiDAR vs camera diverges when the camera lags; cross-correlation recovers the offset from the two signals.", controls: [
        { key: "offset", label: "Camera lag", type: "range", min: -400, max: 400, step: 20, unit: "ms", default: 120 }, { key: "noise", label: "Measurement noise", type: "range", min: 0, max: 1.5, step: 0.05, unit: "m", default: 0.3 }, { key: "speed", label: "Object speed", type: "range", min: 1, max: 30, step: 1, unit: "m/s", default: 12 } ],
        legend: [{ color: c.live, label: "LiDAR track" }, { color: c.ref, label: "Camera track" }, { color: c.bad, label: "Difference" }, { color: c.ok, label: "Cross-correlation" }],
        assumptions: "Single object, single lateral coordinate, uniform 50 Hz sampling. Real logs need per-message timestamps and interpolation before correlation.", camera: "Static plots", libs: [lib.canvas], load: () => import("../engines/driving/CalibTimeOffset") },
    ],
  },
  {
    id: "hd-map", domain: "driving", title: "HD map (OpenDRIVE)", question: "Can the map be read, queried for lane topology and routed on — without a server?", input: "OpenDRIVE .xodr (sample loop with exit, or your file)", output: "Lane surfaces, lane graph, shortest lane route",
    demos: [
      { id: "render", title: "OpenDRIVE → 3D", summary: "A minimal OpenDRIVE reader (line/arc planView, lane sections, road links) renders lane surfaces, markings, reference lines and a vehicle following lane successors.", controls: [
        { key: "speed", label: "Vehicle speed", type: "range", min: 2, max: 30, step: 1, unit: "m/s", default: 12 }, { key: "refLine", label: "Reference lines", type: "toggle", default: true }, { key: "centers", label: "Lane centers", type: "toggle", default: true }, { key: "file", label: "Open .xodr", type: "file", accept: ".xodr,.xml", hint: "line and arc geometries, constant lane widths" } ],
        legend: [{ color: "#13202f", label: "Driving lane" }, { color: "#1f2a3a", label: "Sidewalk" }, { color: c.live, label: "Reference line" }, { color: c.ok, label: "Lane center" }, { color: c.ref, label: "Vehicle" }],
        assumptions: "Spirals, polynomial widths, elevation and superelevation are not parsed; lanes are linked by matching ids across road links. Enough for a loop, not for a real city.", libs: [lib.opendrive, lib.three], load: () => import("../engines/driving/OpenDriveView") },
      { id: "topology", title: "Lane topology query", summary: "Click any driving lane to highlight its predecessors, successors and lane-change neighbours — the adjacency every planner and map-matcher depends on.", controls: [
        { key: "labels", label: "Lane labels", type: "toggle", default: true }, { key: "arrows", label: "Direction arrows", type: "toggle", default: true }, { key: "file", label: "Open .xodr", type: "file", accept: ".xodr,.xml", hint: "same reader as the 3D view" } ],
        legend: [{ color: c.live, label: "Selected" }, { color: c.ok, label: "Successor" }, { color: c.ref, label: "Predecessor" }, { color: c.violet, label: "Neighbour" }],
        assumptions: "Junction connecting roads are treated as ordinary roads; lane ids are linked one-to-one across links.", camera: "Click a lane", libs: [lib.opendrive, lib.canvas], load: () => import("../engines/driving/LaneTopology") },
      { id: "route", title: "Lane-level routing", summary: "Dijkstra over the lane graph where lane changes cost less than staying in lane; the route is animated and lane-change count is reported.", controls: [
        { key: "from", label: "From lane", type: "select", options: ["1:-1", "1:-2", "2:-1", "3:-1", "3:-2", "4:-1", "4:-2"].map((v) => ({ value: v, label: v })), default: "3:-2" }, { key: "to", label: "To lane", type: "select", options: ["1:-1", "1:-2", "2:-2", "3:-1", "4:-1", "4:-2", "5:-1"].map((v) => ({ value: v, label: v })), default: "5:-1" }, { key: "speed", label: "Animation speed", type: "range", min: 5, max: 40, step: 1, unit: "m/s", default: 15 }, { key: "file", label: "Open .xodr", type: "file", accept: ".xodr,.xml", hint: "lane keys are road:lane; selects still list the sample" } ],
        legend: [{ color: c.ok, label: "Route" }, { color: c.live, label: "Start" }, { color: c.bad, label: "Goal" }, { color: c.ref, label: "Vehicle" }],
        assumptions: "Edge cost is lane length; lane-change edges cost 0.4× length. No traffic rules, speed limits or turn restrictions.", camera: "Static map", libs: [lib.opendrive, lib.canvas], load: () => import("../engines/driving/LaneRoute") },
    ],
  },
];
