import { c, lib, type SceneDef } from "../types";

const jointCtls = ["shoulder_pan", "shoulder_lift", "elbow", "wrist_1", "wrist_2", "wrist_3"].map((k) => ({ key: k, label: k.replace("_", " "), type: "range" as const, min: -3.1, max: 3.1, step: 0.01, unit: "rad", default: k === "shoulder_lift" ? -0.6 : k === "elbow" ? 1.2 : k === "wrist_1" ? 0.6 : 0 }));

export const embodied: SceneDef[] = [
  {
    id: "episode-review", domain: "embodied", title: "Episode review", question: "Can a robot-learning episode be watched, scanned and labeled as fast as a video?", input: "24 synthetic LeRobot-style episodes (cameras, joint state, gripper, reward)", output: "Synchronized player, thumbnail wall with anomaly scores, success labels",
    demos: [
      { id: "player", title: "Episode player", summary: "Two camera streams, joint-position and gripper plots, and cumulative reward, all driven by one scrubber — the Rerun / LeRobot visualizer layout.", controls: [{ key: "episode", label: "Episode", type: "range", min: 1, max: 24, step: 1, default: 3 }, { key: "rate", label: "Playback rate", type: "range", min: 0.25, max: 3, step: 0.25, unit: "×", default: 1 }],
        legend: [{ color: c.live, label: "Joint q0 / gripper" }, { color: c.ref, label: "Cube / gripper action" }, { color: c.ok, label: "Success reward" }, { color: c.bad, label: "Failure reward" }],
        assumptions: "Frames are drawn procedurally from joint state (no real video). Episode schema mirrors observation.state / action / reward columns.", camera: "Drag the timeline", libs: [lib.canvas, lib.lerobot, lib.rerun], load: () => import("../engines/embodied/EpisodePlayer") },
      { id: "grid", title: "Episode grid + anomaly", summary: "Every episode as a live thumbnail with a success badge and an anomaly score bar; sort by anomaly or failures and threshold to find what to watch.", controls: [{ key: "sort", label: "Sort", type: "select", options: [{ value: "id", label: "By id" }, { value: "anomaly", label: "By anomaly" }, { value: "failures", label: "Failures first" }], default: "anomaly" }, { key: "threshold", label: "Anomaly threshold", type: "range", min: 0.2, max: 1.4, step: 0.05, default: 0.8 }, { key: "onlyFlagged", label: "Only flagged", type: "toggle", default: false }],
        legend: [{ color: c.ok, label: "Success" }, { color: c.bad, label: "Failure / flagged" }, { color: c.live, label: "Anomaly bar" }],
        assumptions: "Anomaly score is jitter + failure prior from the generator, not a learned detector.", camera: "Grid", libs: [lib.canvas, lib.lerobot], load: () => import("../engines/embodied/EpisodeGrid") },
      { id: "labels", title: "Success labeling", summary: "Label episodes with a failure taxonomy, compare against the reward-threshold auto-detector and the hidden truth, and watch per-task success rates build up.", controls: [{ key: "threshold", label: "Auto-detector return threshold", type: "range", min: 0.2, max: 2, step: 0.05, default: 1 }],
        legend: [{ color: c.ok, label: "Success" }, { color: c.bad, label: "Failure" }],
        assumptions: "Truth comes from the generator; the demo scores human vs auto agreement, which is what a labeling QA loop measures.", camera: "Buttons", libs: [lib.lerobot], load: () => import("../engines/embodied/SuccessLabel") },
    ],
  },
  {
    id: "mujoco", domain: "embodied", title: "MuJoCo in the browser", question: "Real contact physics without a server — how far does MuJoCo WASM go on a laptop?", input: "MJCF models written for this platform (humanoid, arm + gripper, drop scene)", output: "Live simulation state, contacts, grasp result, randomization spread",
    demos: [
      { id: "humanoid", title: "Humanoid stand & push", summary: "Ten position actuators hold a standing pose; apply a push, lower the PD gain or crouch and watch the balance fail — real MuJoCo contacts stepped at 200 Hz in WebAssembly.", controls: [{ key: "kp", label: "PD gain kp", type: "range", min: 5, max: 300, step: 5, default: 80 }, { key: "crouch", label: "Crouch", type: "range", min: 0, max: 0.8, step: 0.02, unit: "rad", default: 0 }, { key: "pushForce", label: "Push force", type: "range", min: 20, max: 400, step: 10, unit: "N", default: 150 }, { key: "timeScale", label: "Time scale", type: "range", min: 0.25, max: 2, step: 0.25, unit: "×", default: 1 }, { key: "push", label: "Push torso", type: "action" }, { key: "reset", label: "Reset pose", type: "action" }],
        legend: [{ color: "#8fb3d9", label: "Body capsules" }, { color: c.ok, label: "Center of mass" }],
        assumptions: "A simplified 10-DoF humanoid, not a menagerie model; no balance controller beyond joint PD, so it falls under moderate pushes. Loads a 8 MB WASM once.", libs: [lib.mujoco, lib.three], load: () => import("../engines/embodied/MjHumanoid") },
      { id: "arm", title: "Arm pick & place", summary: "A 5-DoF arm with a parallel gripper runs a scripted pick-and-place on a cube, or follows your joint sliders; contacts are drawn and grasp success is detected from the cube height.", controls: [{ key: "script", label: "Scripted pick & place", type: "toggle", default: true }, { key: "contacts", label: "Show contacts", type: "toggle", default: true }, { key: "j1", label: "j1 base", type: "range", min: -2.9, max: 2.9, step: 0.01, unit: "rad", default: 0 }, { key: "j2", label: "j2 shoulder", type: "range", min: -1.7, max: 1.7, step: 0.01, unit: "rad", default: 0.9 }, { key: "j3", label: "j3 elbow", type: "range", min: -2.6, max: 2.6, step: 0.01, unit: "rad", default: 0.9 }, { key: "j4", label: "j4 wrist", type: "range", min: -2, max: 2, step: 0.01, unit: "rad", default: 0.5 }, { key: "j5", label: "j5 roll", type: "range", min: -3.1, max: 3.1, step: 0.01, unit: "rad", default: 0 }, { key: "grip", label: "Gripper open", type: "range", min: 0, max: 1, step: 0.05, default: 1 }],
        legend: [{ color: c.ref, label: "Cube" }, { color: c.bad, label: "Contact point" }, { color: "#8fb3d9", label: "Links" }],
        assumptions: "Position actuators with hand-tuned gains; the script is a keyframe table, not a planner. Grasp relies on friction settings in the MJCF.", libs: [lib.mujoco, lib.three], load: () => import("../engines/embodied/MjArm") },
      { id: "randomize", title: "Domain randomization", summary: "The same drop scene compiled three times with friction, mass and restitution scaled by ±spread, simulated side by side — the visual argument for randomizing before sim-to-real.", controls: [{ key: "friction", label: "Friction μ", type: "range", min: 0.1, max: 1.5, step: 0.05, default: 0.8 }, { key: "mass", label: "Mass", type: "range", min: 0.05, max: 1, step: 0.05, unit: "kg", default: 0.2 }, { key: "restitution", label: "Restitution", type: "range", min: 0, max: 0.9, step: 0.05, default: 0.3 }, { key: "spread", label: "Randomization spread", type: "range", min: 0, max: 0.9, step: 0.05, default: 0.5 }],
        legend: [{ color: c.live, label: "Cube" }, { color: c.ref, label: "Sphere" }, { color: c.violet, label: "Capsule" }],
        assumptions: "Restitution is approximated through solref stiffness; MuJoCo's soft contacts are not a coefficient-of-restitution model. Scenes reset every 6 s.", libs: [lib.mujoco, lib.three, lib.isaac], load: () => import("../engines/embodied/MjRandomize") },
    ],
  },
  {
    id: "robot-inspector", domain: "embodied", title: "Robot inspector (URDF)", question: "Given a URDF, can I see the joints, limits, frames, collision shapes and the reachable workspace immediately?", input: "URDF with primitive geometry (built-in 6-DoF arm or upload)", output: "Articulated model, kinematic tree, TCP pose, reachability cloud",
    demos: [
      { id: "urdf", title: "URDF viewer + joints", summary: "urdf-loader parses the robot description into an articulated Three.js model; sliders drive each joint within its limits, axis arrows and the TCP frame are drawn.", controls: [{ key: "animate", label: "Animate joints", type: "toggle", default: true }, { key: "axes", label: "Joint axes & names", type: "toggle", default: true }, ...jointCtls, { key: "file", label: "Open .urdf", type: "file", accept: ".urdf,.xml", hint: "primitive geometry (box / cylinder / sphere); mesh files are not resolved" }],
        legend: [{ color: "#5a9ed9", label: "Links" }, { color: c.ref, label: "Joint axis / tool" }, { color: c.live, label: "TCP frame" }],
        assumptions: "Meshes referenced by package:// paths are skipped; only primitive visuals render. Joint limits come from the URDF.", libs: [lib.urdf, lib.three], load: () => import("../engines/embodied/UrdfInspector") },
      { id: "tree", title: "TF & collision tree", summary: "The kinematic chain as an indented list, a frame per link, and collision geometry as green wireframes; click a link to isolate it while the arm animates.", controls: [{ key: "frames", label: "Show frames", type: "toggle", default: true }, { key: "collision", label: "Show collision shapes", type: "toggle", default: true }],
        legend: [{ color: c.ok, label: "Collision wireframe" }, { color: c.live, label: "Link frame (x/y/z)" }],
        assumptions: "Collision shapes here equal the visuals; real robots ship simplified hulls. TF tree is static (no ROS).", camera: "Click a link in the list", libs: [lib.urdf, lib.three], load: () => import("../engines/embodied/TfTree") },
      { id: "reach", title: "Reachability cloud", summary: "Random joint configurations within limits are pushed through the URDF forward kinematics; the TCP positions accumulate into a workspace cloud colored by distance to joint limits.", controls: [{ key: "rate", label: "Samples per frame", type: "range", min: 10, max: 400, step: 10, default: 120 }, { key: "floor", label: "Floor cut", type: "range", min: -0.5, max: 0.5, step: 0.05, unit: "m", default: 0 }, { key: "lockWrist", label: "Lock wrist joints", type: "toggle", default: false }, { key: "showArm", label: "Show arm", type: "toggle", default: true }],
        legend: [{ color: c.live, label: "Far from limits" }, { color: c.bad, label: "Near a limit" }],
        assumptions: "Uniform sampling in joint space, not in Cartesian space, so density is not a manipulability measure. Self-collision is not checked.", libs: [lib.urdf, lib.three], load: () => import("../engines/embodied/Reachability") },
    ],
  },
  {
    id: "kinematics", domain: "embodied", title: "Kinematics", question: "How do analytic IK and a phase-driven gait look before any physics is involved?", input: "Target position, gait parameters", output: "Solved arm pose, walking skeleton with center of mass",
    demos: [
      { id: "arm", title: "Two-link IK", summary: "Planar two-link arm with analytic inverse kinematics and both elbow branches; joints servo toward the solution with a first-order lag.", controls: [{ key: "targetX", label: "Target X", type: "range", min: -4.5, max: 4.5, step: 0.05, unit: "m", default: 2.4 }, { key: "targetY", label: "Target Y", type: "range", min: -1, max: 4.5, step: 0.05, unit: "m", default: 2.2 }, { key: "elbowUp", label: "Elbow-up solution", type: "toggle", default: true }, { key: "trace", label: "Trace end effector", type: "toggle", default: true }],
        legend: [{ color: c.live, label: "Links (solved pose)" }, { color: c.ref, label: "Target" }, { color: c.muted, label: "Reachable annulus" }],
        assumptions: "Links 2.4 m and 1.8 m, no dynamics or collision.", libs: [lib.three], load: () => import("../engines/embodied/Arm") },
      { id: "gait", title: "Walking gait", summary: "Kinematic biped gait driven by phase; sinusoidal joint templates, mass-weighted center of mass and support-foot highlighting.", controls: [{ key: "cadence", label: "Cadence", type: "range", min: 60, max: 180, step: 2, unit: "spm", default: 110 }, { key: "stride", label: "Stride length", type: "range", min: 0.3, max: 1.4, step: 0.02, unit: "m", default: 0.8 }, { key: "kneeAmp", label: "Knee flexion", type: "range", min: 20, max: 80, step: 1, unit: "°", default: 55 }, { key: "armSwing", label: "Arm swing", type: "range", min: 0, max: 40, step: 1, unit: "°", default: 22 }, { key: "trace", label: "Trace center of mass", type: "toggle", default: true }],
        legend: [{ color: c.live, label: "Skeleton" }, { color: c.ok, label: "Center of mass" }, { color: c.ref, label: "Support foot" }],
        assumptions: "No ground reaction forces; templates fit to typical human walking.", libs: [lib.three], load: () => import("../engines/embodied/Gait") },
    ],
  },
  {
    id: "policy-monitor", domain: "embodied", title: "Policy monitor", question: "While a policy trains or runs, what should be on the screen: the envs, the reward terms, or what the policy looks at?", input: "64 vectorized cart-pole envs, shaped reward terms, patch attention", output: "Env grid + training curve, reward decomposition, attention heatmap",
    demos: [
      { id: "envs", title: "Parallel envs (64)", summary: "64 cart-pole environments stepped in lockstep; a linear policy improves by random-search hill climbing on the mean return. The grid view is what Isaac Lab / Viser show, at toy scale.", controls: [{ key: "stepsPerFrame", label: "Sim steps per frame", type: "range", min: 1, max: 20, step: 1, default: 6 }, { key: "noise", label: "Search noise", type: "range", min: 0.05, max: 2, step: 0.05, default: 0.6 }],
        legend: [{ color: c.live, label: "Cart" }, { color: c.ref, label: "Pole (alive)" }, { color: c.bad, label: "Pole (terminated)" }, { color: c.ok, label: "Mean return" }],
        assumptions: "Random search on a 4-weight linear policy, not PPO; cart-pole is the classic Gym dynamics with a 0.02 s step.", camera: "Grid + curve", libs: [lib.canvas, lib.isaac, lib.viser], load: () => import("../engines/embodied/ParallelEnvs") },
      { id: "reward", title: "Reward decomposition", summary: "Total reward split into reach / grasp / lift / penalty over training; re-weight the terms and watch which one dominates each phase.", controls: [{ key: "wReach", label: "Reach weight", type: "range", min: 0, max: 3, step: 0.1, default: 1 }, { key: "wGrasp", label: "Grasp weight", type: "range", min: 0, max: 3, step: 0.1, default: 1.5 }, { key: "wLift", label: "Lift weight", type: "range", min: 0, max: 3, step: 0.1, default: 2 }, { key: "wPenalty", label: "Penalty weight", type: "range", min: 0, max: 3, step: 0.1, default: 1 }],
        legend: [{ color: c.live, label: "Reach" }, { color: c.ref, label: "Grasp" }, { color: c.ok, label: "Lift" }, { color: c.bad, label: "Penalty" }, { color: c.fg, label: "Total" }],
        assumptions: "Term curves are synthetic templates of a typical curriculum; the point is the decomposition view, not the numbers.", camera: "Static charts", libs: [lib.canvas], load: () => import("../engines/embodied/RewardDecomposition") },
      { id: "attention", title: "Attention overlay", summary: "Patch-level policy attention drawn over the camera frame as a heatmap; on failure episodes the peak drifts away from the object — the diagnostic a monitor should surface.", controls: [{ key: "episode", label: "Episode", type: "range", min: 1, max: 24, step: 1, default: 2 }, { key: "patches", label: "Patch grid", type: "range", min: 6, max: 24, step: 2, default: 14 }, { key: "temperature", label: "Softmax temperature", type: "range", min: 0.2, max: 3, step: 0.1, default: 1 }, { key: "opacity", label: "Heatmap opacity", type: "range", min: 0.1, max: 0.9, step: 0.05, default: 0.5 }],
        legend: [{ color: c.bad, label: "High attention" }, { color: c.live, label: "Low attention" }, { color: c.fg, label: "Peak patch" }],
        assumptions: "Attention is synthesized from object position with drift on failures; a real overlay would come from ViT attention rollout or grad-CAM.", camera: "Image", libs: [lib.canvas, lib.lerobot], load: () => import("../engines/embodied/AttentionOverlay") },
    ],
  },
];
