import { c, lib, type SceneDef } from "../types";

export const dataloop: SceneDef[] = [
  { id: "pipeline", domain: "dataloop", title: "Pipeline status", question: "Where does the data loop stall — and how many frames actually reach training?", input: "Ingest rate, QA capacity, failure rate", output: "Live flow with backlog, per-stage counts, survival funnel",
    demos: [{ id: "flow", title: "Flow + funnel", summary: "Batches move from fleet logs to deploy through nine stages; capacity-limited human QA becomes the bottleneck and the funnel shows survival to training.", controls: [{ key: "rate", label: "Ingest rate", type: "range", min: 1, max: 20, step: 1, unit: "batches/s", default: 8 }, { key: "qaCapacity", label: "QA capacity (parallel)", type: "range", min: 1, max: 30, step: 1, default: 6 }, { key: "failRate", label: "Stage failure rate", type: "range", min: 0, max: 0.3, step: 0.01, default: 0.05 }], legend: [{ color: c.live, label: "Batch" }, { color: c.ref, label: "Batch in QA" }, { color: c.bad, label: "Backlogged stage" }], assumptions: "Stages are abstract; durations are uniform except QA. Failed batches are dropped, not retried.", camera: "Static flow", libs: [lib.canvas, lib.d3], load: () => import("../engines/dataloop/Pipeline") }] },
  { id: "dataset", domain: "dataloop", title: "Dataset statistics", question: "Is the dataset balanced, where is the long tail, and what changed between versions?", input: "Two dataset versions with class and attribute counts", output: "Class histogram (log), attribute mix, version diff",
    demos: [{ id: "stats", title: "Distributions + version diff", summary: "Class histogram with a log toggle to expose the long tail, weather / time / region mixes, and a v12 → v13 diff that shows targeted tail collection.", controls: [{ key: "version", label: "Version", type: "select", options: [{ value: "v12", label: "v12" }, { value: "v13", label: "v13" }], default: "v13" }, { key: "log", label: "Log scale", type: "toggle", default: true }, { key: "diff", label: "Show Δ vs v12", type: "toggle", default: true }], legend: [{ color: c.live, label: "Head class" }, { color: c.ref, label: "Tail class" }, { color: c.ok, label: "Added" }], assumptions: "Counts are synthetic with an exponential head/tail profile.", camera: "Static charts", libs: [lib.canvas, lib.plotly], load: () => import("../engines/dataloop/DatasetStats") }] },
  { id: "training", domain: "dataloop", title: "Training runs", question: "Which run is winning, and when did the diverging one leave the pack?", input: "Four runs: loss, val mAP, learning-rate schedule", output: "Smoothed curves, best run, divergence flag",
    demos: [{ id: "runs", title: "Run comparison + divergence", summary: "Loss / mAP / LR for four runs with smoothing and run toggles; a divergence detector flags the run whose loss leaves the median envelope for 10 steps.", controls: [{ key: "smooth", label: "Smoothing window", type: "range", min: 1, max: 40, step: 1, default: 8 }, { key: "divergence", label: "Divergence threshold", type: "range", min: 0.05, max: 1, step: 0.05, default: 0.25 }, { key: "r0", label: "baseline", type: "toggle", default: true }, { key: "r1", label: "+tail-data", type: "toggle", default: true }, { key: "r2", label: "lr 3e-3", type: "toggle", default: true }, { key: "r3", label: "+aug", type: "toggle", default: true }], legend: [{ color: c.muted, label: "baseline" }, { color: c.live, label: "+tail-data" }, { color: c.ref, label: "lr 3e-3" }, { color: c.ok, label: "+aug" }], assumptions: "Curves are synthetic (warmup + cosine, one run diverging after step 220).", camera: "Static charts", libs: [lib.canvas, lib.uplot], load: () => import("../engines/dataloop/TrainingRuns") }] },
];

export const spatial: SceneDef[] = [
  { id: "viewer", domain: "spatial", title: "3D viewer", question: "Inspect a glTF or a splat scene in the browser with the same controls.", input: "Local .glb (stays on device) or a synthetic splat scene", output: "Turntable, wireframe, exploded view; sorted Gaussian billboards",
    demos: [
      { id: "gltf", title: "glTF inspector", summary: "GLTFLoader with turntable, wireframe and an exploded view of parts; open your own .glb.", controls: [{ key: "file", label: "Open a local .glb", type: "file", accept: ".glb,model/gltf-binary", hint: "Self-contained glTF 2.0 binary, ≤ 60 MB. Stays on your device." }, { key: "wireframe", label: "Wireframe", type: "toggle", default: false }, { key: "turntable", label: "Turntable", type: "toggle", default: true }, { key: "exploded", label: "Explode parts", type: "range", min: 0, max: 1, step: 0.01, default: 0 }], legend: [{ color: c.live, label: "Mesh" }, { color: c.muted, label: "Bounds" }], assumptions: "Draco / KTX2 compressed assets are not decoded in this build.", libs: [lib.three, lib.gltf], load: () => import("../engines/spatial/ModelViewer") },
      { id: "splats", title: "Gaussian splats (toy)", summary: "Thousands of anisotropic Gaussian billboards with per-frame back-to-front sorting and alpha compositing — the rendering idea behind 3DGS on a synthetic scene.", controls: [{ key: "count", label: "Splats", type: "range", min: 2000, max: 40000, step: 2000, default: 24000 }, { key: "size", label: "Size ×", type: "range", min: 0.2, max: 2, step: 0.1, default: 0.8 }, { key: "opacity", label: "Opacity", type: "range", min: 0.1, max: 1, step: 0.05, default: 0.8 }, { key: "sort", label: "Depth sort", type: "toggle", default: true }, { key: "turntable", label: "Turntable", type: "toggle", default: true }], legend: [{ color: c.live, label: "Column" }, { color: c.ref, label: "Sphere" }, { color: "#27394f", label: "Ground" }], assumptions: "Isotropic-ish 2-D Gaussians, CPU sort; real 3DGS uses full 3-D covariances and GPU radix sort.", libs: [lib.three, lib.splat], load: () => import("../engines/spatial/Splats") },
    ] },
];

export const ai: SceneDef[] = [
  { id: "inside-models", domain: "ai", title: "Inside models", question: "Attention, embeddings and an agent's trace — the three views that explain what a model did.", input: "A sentence, 600 vectors, an agent run", output: "Attention arcs + matrix, 2-D embedding map, span timeline",
    demos: [
      { id: "attention", title: "Self-attention", summary: "Toy transformer head over your sentence: causal mask, temperature, arcs and matrix.", controls: [{ key: "text", label: "Sentence", type: "text", default: "the robot picked up the red cube because it was closest", hint: "Up to 16 tokens" }, { key: "head", label: "Attention head", type: "range", min: 0, max: 3, step: 1, default: 0 }, { key: "temperature", label: "Softmax temperature", type: "range", min: 0.2, max: 3, step: 0.05, default: 1 }, { key: "causal", label: "Causal mask", type: "toggle", default: true }], legend: [{ color: c.live, label: "Attention weight" }], assumptions: "Deterministic hashed embeddings, not a trained model.", camera: "Static", libs: [lib.canvas, lib.d3], load: () => import("../engines/ai/Attention") },
      { id: "embeddings", title: "Embedding map", summary: "32-d vectors from six clusters laid out in 2-D by an in-browser kNN force layout; hover for neighbours, purity is measured.", controls: [{ key: "attraction", label: "kNN attraction", type: "range", min: 0.1, max: 3, step: 0.1, default: 1 }, { key: "repulsion", label: "Repulsion", type: "range", min: 1, max: 40, step: 1, default: 12 }], legend: [{ color: c.live, label: "car" }, { color: c.bad, label: "pedestrian" }, { color: c.ref, label: "cone" }, { color: c.violet, label: "night" }, { color: c.ok, label: "rain" }], assumptions: "Force layout, not t-SNE/UMAP; O(n²) repulsion so n is capped at 600.", camera: "Hover points", libs: [lib.canvas, lib.d3], load: () => import("../engines/ai/Embeddings") },
      { id: "agent", title: "Agent trace", summary: "An agent run (plan → tool → observation → reflect → answer) with a nested sub-agent replayed as a span timeline with tokens, latency, cost and a failed tool call.", controls: [{ key: "speed", label: "Replay speed", type: "range", min: 0.25, max: 4, step: 0.25, unit: "×", default: 1 }, { key: "price", label: "Price per 1M tokens", type: "range", min: 0.5, max: 30, step: 0.5, unit: "USD", default: 6 }], legend: [{ color: c.violet, label: "Plan" }, { color: c.live, label: "Tool" }, { color: c.muted, label: "Observation" }, { color: c.ref, label: "Reflect" }, { color: c.ok, label: "Answer" }], assumptions: "A fixed illustrative trace; a real tracer ingests OpenTelemetry spans.", camera: "Timeline", libs: [lib.canvas], load: () => import("../engines/ai/AgentTrace") },
    ] },
];

export const markets: SceneDef[] = [
  { id: "microstructure", domain: "markets", title: "Market microstructure", question: "Order book, volatility surface and liquidation levels — three structures behind one price.", input: "Order arrivals, vol parameters, leveraged positions", output: "Live depth chart, 3-D IV surface, liquidation heatmap",
    demos: [
      { id: "orderbook", title: "Limit order book", summary: "Simulated LOB with arrivals, cancellations and market orders; depth chart and sweep button.", controls: [{ key: "arrival", label: "Order arrival rate", type: "range", min: 5, max: 120, step: 5, unit: "/s", default: 40 }, { key: "volatility", label: "Volatility", type: "range", min: 0, max: 2, step: 0.05, default: 0.6 }, { key: "aggression", label: "Market-order share", type: "range", min: 0, max: 0.6, step: 0.02, default: 0.2 }, { key: "sweep", label: "Sweep size", type: "range", min: 1, max: 60, step: 1, default: 15 }], legend: [{ color: c.ok, label: "Bids" }, { color: c.bad, label: "Asks" }], assumptions: "Synthetic flow, not exchange data.", camera: "Static", libs: [lib.canvas, lib.ldjs], load: () => import("../engines/markets/OrderBook") },
      { id: "volsurface", title: "IV surface", summary: "An SVI-style smile per expiry with term structure as a live 3-D mesh; skew, curvature and a front-month shock deform it.", controls: [{ key: "base", label: "ATM base IV", type: "range", min: 0.1, max: 0.8, step: 0.01, default: 0.28 }, { key: "skew", label: "Skew", type: "range", min: -0.6, max: 0.6, step: 0.02, default: -0.25 }, { key: "curv", label: "Curvature", type: "range", min: 0, max: 2, step: 0.05, default: 0.8 }, { key: "term", label: "Term slope", type: "range", min: -0.5, max: 0.5, step: 0.02, default: 0.1 }, { key: "shock", label: "Front-month shock", type: "range", min: 0, max: 0.3, step: 0.01, default: 0.08 }], legend: [{ color: "#27394f", label: "Low IV" }, { color: c.live, label: "Mid" }, { color: c.bad, label: "High" }], assumptions: "Parametric surface, no arbitrage checks.", libs: [lib.three], load: () => import("../engines/markets/VolSurface") },
      { id: "liquidation", title: "Liquidation heatmap", summary: "Leveraged positions opened along a random walk imply liquidation bands; price is nudged toward the densest band (liquidity hunting) and clears it.", controls: [{ key: "leverage", label: "Leverage", type: "range", min: 2, max: 50, step: 1, unit: "×", default: 10 }, { key: "bias", label: "Long bias", type: "range", min: -0.4, max: 0.4, step: 0.05, default: 0.1 }, { key: "vol", label: "Volatility", type: "range", min: 0.2, max: 3, step: 0.1, default: 1 }, { key: "hunt", label: "Liquidity hunting", type: "range", min: 0, max: 1, step: 0.05, default: 0.4 }, { key: "speed", label: "Speed", type: "range", min: 1, max: 20, step: 1, unit: "×", default: 6 }], legend: [{ color: c.live, label: "Long liquidations" }, { color: c.bad, label: "Short liquidations" }, { color: c.ref, label: "Price" }], assumptions: "Toy model; no funding, fees or partial liquidation.", camera: "Static", libs: [lib.canvas], load: () => import("../engines/markets/Liquidation") },
    ] },
];

export const science: SceneDef[] = [
  { id: "dynamics", domain: "science", title: "Dynamics & fields", question: "Chaos in three ODEs and interference in a wave field — two classic simulations, live.", input: "σ ρ β and initial spread; wave speed, damping, sources", output: "Diverging attractor trajectories, wave interference pattern",
    demos: [
      { id: "lorenz", title: "Lorenz attractor", summary: "24 RK4-integrated trajectories from nearby initial conditions; their separation estimates the Lyapunov exponent.", controls: [{ key: "sigma", label: "σ", type: "range", min: 1, max: 20, step: 0.5, default: 10 }, { key: "rho", label: "ρ", type: "range", min: 1, max: 60, step: 0.5, default: 28 }, { key: "beta", label: "β", type: "range", min: 0.5, max: 5, step: 0.1, default: 2.667 }, { key: "spread", label: "Initial spread", type: "range", min: 0.1, max: 10, step: 0.1, unit: "×1e-3", default: 4 }, { key: "speed", label: "Speed", type: "range", min: 0.5, max: 8, step: 0.5, unit: "×", default: 5 }], legend: [{ color: c.live, label: "Trajectory (hue = index)" }], assumptions: "Fixed step h = 0.005 RK4; Lyapunov estimate is crude.", libs: [lib.three], load: () => import("../engines/science/Lorenz") },
      { id: "waves", title: "Wave field", summary: "2-D wave equation on a 160² grid with finite differences, damping, click-to-add sources and a double-slit obstacle.", controls: [{ key: "c", label: "Wave speed", type: "range", min: 0.1, max: 0.7, step: 0.02, default: 0.45 }, { key: "freq", label: "Source frequency", type: "range", min: 1, max: 12, step: 0.5, default: 5 }, { key: "damping", label: "Damping", type: "range", min: 0, max: 0.02, step: 0.001, default: 0.003 }, { key: "substeps", label: "Substeps / frame", type: "range", min: 1, max: 8, step: 1, default: 3 }, { key: "slit", label: "Double slit", type: "toggle", default: true }], legend: [{ color: c.bad, label: "Crest" }, { color: "#0c1628", label: "Trough" }], assumptions: "CFL stability requires c ≤ 0.7; edges are crudely absorbing.", camera: "Click to add sources", libs: [lib.canvas], load: () => import("../engines/science/Field") },
    ] },
];

export const industry: SceneDef[] = [
  { id: "networks", domain: "industry", title: "Industrial networks", question: "Power flow on a grid and disruption on a supply chain — both are graphs with capacity.", input: "Generator / load setpoints, line trips; supplier graph, knockouts", output: "Line loadings and overloads; health propagation",
    demos: [
      { id: "power", title: "DC power flow", summary: "9-bus network solved as B·θ = P every frame; line flows animate, overloads turn red, and tripping a line re-routes power.", controls: [{ key: "load", label: "Total load", type: "range", min: 1, max: 12, step: 0.5, unit: "p.u.", default: 6 }, { key: "gen0", label: "Gen at bus 1", type: "range", min: 0, max: 8, step: 0.5, default: 3 }, { key: "gen7", label: "Gen at bus 8", type: "range", min: 0, max: 8, step: 0.5, default: 2 }, { key: "gen8", label: "Gen at bus 9 (hub)", type: "range", min: 0, max: 8, step: 0.5, default: 1 }, { key: "trip", label: "Trip line", type: "range", min: 0, max: 12, step: 1, default: 0 }], legend: [{ color: c.ok, label: "Generator" }, { color: c.ref, label: "Load" }, { color: c.bad, label: "Overload / tripped" }], assumptions: "Lossless DC approximation; bus 1 is the slack reference.", camera: "Static graph", libs: [lib.canvas, lib.d3], load: () => import("../engines/industry/PowerFlow") },
      { id: "supply", title: "Supply-chain disruption", summary: "Four-tier supplier graph; knock out a node and watch health propagate through single-sourced edges with a lead-time lag. Redundancy changes the topology.", controls: [{ key: "redundancy", label: "Dual-sourcing probability", type: "range", min: 0, max: 1, step: 0.05, default: 0.35 }, { key: "leadTime", label: "Lead time", type: "range", min: 0.5, max: 8, step: 0.5, unit: "s", default: 2 }, { key: "target", label: "Target node", type: "range", min: 1, max: 17, step: 1, default: 9 }, { key: "knock", label: "Knock out node", type: "action" }, { key: "restore", label: "Restore all", type: "action" }], legend: [{ color: c.ok, label: "Healthy" }, { color: c.bad, label: "Impaired / disrupted edge" }, { color: c.ref, label: "Single-sourced edge" }], assumptions: "Health is min over single sources, max over dual sources; no inventory buffers.", camera: "Static graph", libs: [lib.canvas, lib.d3], load: () => import("../engines/industry/SupplyChain") },
    ] },
];
