import { c, lib, type SceneDef } from "../types";

const kindSel = { key: "kind", label: "Event kind", type: "select" as const, options: [{ value: "all", label: "All kinds" }, { value: "hard_brake", label: "Hard brake" }, { value: "disengagement", label: "Disengagement" }, { value: "sensor_dropout", label: "Sensor dropout" }, { value: "swerve", label: "Swerve" }, { value: "cut_in", label: "Cut-in" }], default: "all" };
const ruleCtls = [
  { key: "brake", label: "Brake threshold", type: "range" as const, min: 0.2, max: 0.9, step: 0.02, default: 0.5 },
  { key: "accel", label: "Deceleration threshold", type: "range" as const, min: 1, max: 7, step: 0.25, unit: "m/s²", default: 3 },
  { key: "dropHz", label: "LiDAR dropout below", type: "range" as const, min: 1, max: 9, step: 0.5, unit: "Hz", default: 5 },
  { key: "steerRate", label: "Steer-rate threshold", type: "range" as const, min: 0.02, max: 0.2, step: 0.01, default: 0.08 },
];

export const triage: SceneDef[] = [
  {
    id: "event-mining", domain: "triage", title: "Event mining", question: "Out of an hour of fleet logs, where are the moments worth a human's time — and how precise are the rules that find them?", input: "6 vehicles × 10 min synthetic logs at 10 Hz with hidden ground-truth events", output: "Event markers, precision / recall, snippet cards",
    demos: [
      { id: "timeline", title: "Fleet event timeline", summary: "One lane per vehicle with rule-mined events as markers, manual-driving spans shaded, ground truth as ticks, and the selected vehicle's raw signals underneath.", controls: [...ruleCtls, { key: "vehicle", label: "Inspect vehicle", type: "range", min: 1, max: 6, step: 1, default: 1 }, { key: "rate", label: "Cursor speed", type: "range", min: 1, max: 40, step: 1, unit: "×", default: 10 }, { key: "showGt", label: "Show ground-truth ticks", type: "toggle", default: true }],
        legend: [{ color: c.bad, label: "Hard brake" }, { color: c.ref, label: "Disengagement" }, { color: c.violet, label: "Sensor dropout" }, { color: c.live, label: "Swerve" }],
        assumptions: "Logs are synthetic with injected events; rules are simple thresholds with a 4 s cooldown. Real mining adds learned detectors and map context.", camera: "Timeline", libs: [lib.canvas, lib.applied, lib.foxgloveApp], load: () => import("../engines/triage/EventTimeline") },
      { id: "rules", title: "Rule editor", summary: "Sweep the brake threshold to see precision vs recall, and a two-threshold F1 heatmap that shows where the current rule sits — the tuning loop behind every event detector.", controls: ruleCtls,
        legend: [{ color: c.live, label: "Precision" }, { color: c.ref, label: "Recall" }, { color: c.bad, label: "High F1" }],
        assumptions: "Precision/recall use a 3 s match window against synthetic ground truth. The heatmap re-runs mining for 144 threshold pairs on load.", camera: "Static charts", libs: [lib.canvas, lib.applied], load: () => import("../engines/triage/RuleEditor") },
      { id: "snippets", title: "Snippet grid", summary: "Every mined event becomes a card: ±N s speed/brake sparkline with the event cursor and a trajectory glyph — the thumbnail wall reviewers scan first.", controls: [kindSel, { key: "window", label: "Window", type: "range", min: 2, max: 10, step: 1, unit: "s", default: 4 }, { key: "brake", label: "Brake threshold", type: "range", min: 0.2, max: 0.9, step: 0.02, default: 0.5 }],
        legend: [{ color: c.live, label: "Speed" }, { color: c.bad, label: "Brake" }, { color: c.ref, label: "Path" }],
        assumptions: "Cards are limited to 60; real walls paginate and pre-render video thumbnails.", camera: "Click a card to expand", libs: [lib.canvas], load: () => import("../engines/triage/SnippetGrid") },
    ],
  },
  {
    id: "review", domain: "triage", title: "Review workbench", question: "How does a reviewer move through a queue of events, decide, classify the root cause and hand the issue off?", input: "Mined events with ±6 s context", output: "Decisions, severity, root-cause statistics, tracker payload",
    demos: [
      { id: "bench", title: "Triage workbench", summary: "Queue on the left, 3D replay of the event window with the ego trail and a pulsing event marker, decision buttons and keyboard flow (j/k, 1-3, t/f/n). Throughput is measured.", controls: [{ key: "follow", label: "Camera follows ego", type: "toggle", default: true }],
        legend: [{ color: c.ref, label: "Ego (recorded)" }, { color: c.live, label: "Trail / lead vehicle" }, { color: c.bad, label: "Event marker / true issue" }],
        assumptions: "Replay uses the synthetic log's position trace; the lead vehicle is a placeholder for brake/cut-in events. Decisions live in memory.", camera: "j / k next · 1-3 severity · t / f / n decide", libs: [lib.three, lib.applied, lib.foxgloveApp], load: () => import("../engines/triage/ReviewBench") },
      { id: "rootcause", title: "Root-cause taxonomy", summary: "Flow from event kind to root cause (perception / planning / localization / control / other) and an initiator × cause matrix — the split that separates driver-initiated from system-flagged issues.", controls: [{ key: "minSeverity", label: "Min severity", type: "range", min: 1, max: 3, step: 1, default: 1 }, { key: "version", label: "Software version", type: "select", options: [{ value: "all", label: "All" }, { value: "v2.3", label: "v2.3" }, { value: "v2.4", label: "v2.4" }], default: "all" }],
        legend: [{ color: c.bad, label: "Hard brake" }, { color: c.ref, label: "Disengagement" }, { color: c.violet, label: "Sensor dropout" }, { color: c.ok, label: "Cut-in" }, { color: c.live, label: "Swerve" }],
        assumptions: "Causes are assigned by the synthetic generator with published proportions (driver-initiated → perception/planning/localization; system-initiated → control).", camera: "Flow diagram", libs: [lib.canvas, lib.d3], load: () => import("../engines/triage/RootCause") },
      { id: "handoff", title: "Issue hand-off", summary: "A reviewed event becomes a tracker-ready payload (Jira / GitHub / generic): title, severity, cause, MCAP pointer with clip range, and a reproduction command.", controls: [{ key: "event", label: "Event", type: "range", min: 0, max: 19, step: 1, default: 3 }, { key: "target", label: "Target", type: "select", options: [{ value: "generic", label: "Generic JSON" }, { value: "jira", label: "Jira fields" }, { value: "github", label: "GitHub issue" }], default: "jira" }, { key: "pre", label: "Clip before", type: "range", min: 1, max: 20, step: 1, unit: "s", default: 6 }, { key: "post", label: "Clip after", type: "range", min: 1, max: 20, step: 1, unit: "s", default: 4 }, { key: "copy", label: "Copy to clipboard", type: "action" }, { key: "download", label: "Download JSON", type: "action" }],
        legend: [{ color: c.live, label: "Payload" }],
        assumptions: "Log URIs and CLI are illustrative; a real integration posts to the tracker API and links back to the review.", camera: "Text preview", libs: [lib.applied], load: () => import("../engines/triage/IssueHandoff") },
    ],
  },
  {
    id: "log-sim", domain: "triage", title: "Log sim (counterfactual)", question: "If the safety driver had not taken over, what would the stack have done — and would it have been safe?", input: "Recorded trajectory up to the disengagement, reactive policy parameters", output: "Counterfactual trajectory, TTC, outcome, policy A/B, outcome matrix",
    demos: [
      { id: "counterfactual", title: "Counterfactual replay", summary: "Recorded ego (amber) is replayed to the disengagement line, then a reactive stack (cyan) continues against a braking lead and a crossing pedestrian; TTC and collision are checked.", controls: [{ key: "reaction", label: "Stack reaction delay", type: "range", min: 0, max: 1.5, step: 0.05, unit: "s", default: 0.4 }, { key: "decel", label: "Max deceleration", type: "range", min: 2, max: 9, step: 0.5, unit: "m/s²", default: 6 }, { key: "ttcThreshold", label: "Brake when TTC <", type: "range", min: 0.5, max: 5, step: 0.1, unit: "s", default: 2.5 }, { key: "pedTime", label: "Pedestrian starts at", type: "range", min: 3, max: 10, step: 0.5, unit: "s", default: 5 }, { key: "allowSwerve", label: "Allow swerve", type: "toggle", default: true }],
        legend: [{ color: c.ref, label: "Recorded (human takeover)" }, { color: c.live, label: "Counterfactual stack" }, { color: c.violet, label: "Lead vehicle" }, { color: c.bad, label: "Pedestrian / disengagement line" }],
        assumptions: "Other agents replay as recorded (open-loop); a closed-loop sim would react to the counterfactual ego. Policy is a TTC-threshold brake with optional swerve.", libs: [lib.three, lib.applied, lib.carla], load: () => import("../engines/triage/Counterfactual") },
      { id: "policies", title: "Policy A/B", summary: "Two reactive policies simulated after the same disengagement against a braking lead: speed, gap and TTC traces with a 1-D outcome strip.", controls: [{ key: "reactA", label: "A · reaction", type: "range", min: 0, max: 1.5, step: 0.05, unit: "s", default: 0.6 }, { key: "decelA", label: "A · decel", type: "range", min: 2, max: 9, step: 0.5, unit: "m/s²", default: 4 }, { key: "ttcA", label: "A · TTC threshold", type: "range", min: 0.5, max: 5, step: 0.1, unit: "s", default: 2 }, { key: "reactB", label: "B · reaction", type: "range", min: 0, max: 1.5, step: 0.05, unit: "s", default: 0.2 }, { key: "decelB", label: "B · decel", type: "range", min: 2, max: 9, step: 0.5, unit: "m/s²", default: 7 }, { key: "ttcB", label: "B · TTC threshold", type: "range", min: 0.5, max: 5, step: 0.1, unit: "s", default: 3 }],
        legend: [{ color: c.live, label: "Policy A" }, { color: c.ref, label: "Policy B" }, { color: c.violet, label: "Lead" }, { color: c.bad, label: "Collision" }],
        assumptions: "Point-mass longitudinal model, constant lead deceleration, no lateral option. Enough to rank policies, not to certify them.", camera: "Static charts", libs: [lib.canvas], load: () => import("../engines/triage/PolicyCompare") },
      { id: "matrix", title: "Outcome matrix", summary: "Reaction delay × initial speed sweep — 196 one-dimensional simulations — colored by minimum gap, red where the stack would have collided; the safe envelope is visible at a glance.", controls: [{ key: "decel", label: "Max deceleration", type: "range", min: 2, max: 9, step: 0.5, unit: "m/s²", default: 6 }, { key: "ttc", label: "Brake when TTC <", type: "range", min: 0.5, max: 5, step: 0.1, unit: "s", default: 2.5 }],
        legend: [{ color: c.bad, label: "Collision" }, { color: c.ref, label: "Small gap" }, { color: c.live, label: "Large gap" }],
        assumptions: "Same 1-D model as the policy A/B; the animated reveal is cosmetic — all cells are computed on parameter change.", camera: "Static grid", libs: [lib.canvas], load: () => import("../engines/triage/OutcomeMatrix") },
    ],
  },
  {
    id: "dashboard", domain: "triage", title: "Fleet dashboard", question: "Is the fleet getting safer week over week, where do events cluster, and did the last release help or hurt?", input: "Fleet events with version, cause, severity and location", output: "Trend chart, hex-density map, version diff",
    demos: [
      { id: "trends", title: "Fleet trends", summary: "26 weeks of disengagements per 1,000 km stacked by cause with a rolling average and weekly km; a control-related regression after the v2.4 rollout is annotated.", controls: [{ key: "window", label: "Rolling window", type: "range", min: 1, max: 8, step: 1, unit: "weeks", default: 4 }, { key: "c0", label: "Perception", type: "toggle", default: true }, { key: "c1", label: "Planning", type: "toggle", default: true }, { key: "c2", label: "Localization", type: "toggle", default: true }, { key: "c3", label: "Control", type: "toggle", default: true }, { key: "c4", label: "Other", type: "toggle", default: true }],
        legend: [{ color: c.live, label: "Perception" }, { color: c.ok, label: "Planning" }, { color: c.violet, label: "Localization" }, { color: c.ref, label: "Control" }, { color: c.muted, label: "Other" }],
        assumptions: "Weekly series is synthetic with an exponential improvement trend and one injected regression.", camera: "Static chart", libs: [lib.canvas, lib.d3], load: () => import("../engines/triage/FleetTrends") },
      { id: "hotspots", title: "Geo hotspots (deck.gl)", summary: "Fleet drive paths and event density as extruded hexagons on a MapLibre dark basemap, rendered with deck.gl's MapLibreOverlay; severity as point color.", controls: [kindSel, { key: "radius", label: "Hex radius", type: "range", min: 100, max: 600, step: 50, unit: "m", default: 250 }, { key: "elevation", label: "Elevation scale", type: "range", min: 5, max: 80, step: 5, default: 30 }, { key: "points", label: "Show event points", type: "toggle", default: true }],
        legend: [{ color: c.live, label: "Drive path" }, { color: c.bad, label: "Dense / S3" }, { color: c.ref, label: "S2" }, { color: c.ok, label: "S1" }],
        assumptions: "Locations are synthetic around San Francisco. Basemap tiles come from Carto's public dark style; no key needed.", camera: "Drag to pan · ctrl-drag to tilt", libs: [lib.deck, lib.maplibre], load: () => import("../engines/triage/GeoHotspots") },
      { id: "versions", title: "Version comparison", summary: "v2.3 vs v2.4 paired bars by event kind or root cause, optionally normalized per 1,000 km, with a delta column shaded by a rough significance test.", controls: [{ key: "dimension", label: "Group by", type: "select", options: [{ value: "kind", label: "Event kind" }, { value: "cause", label: "Root cause" }], default: "cause" }, { key: "normalize", label: "Per 1,000 km", type: "toggle", default: true }, { key: "minSeverity", label: "Min severity", type: "range", min: 1, max: 3, step: 1, default: 1 }],
        legend: [{ color: c.ref, label: "v2.3" }, { color: c.live, label: "v2.4" }, { color: c.ok, label: "Improved" }, { color: c.bad, label: "Regressed" }],
        assumptions: "Odd vehicles run v2.3, even run v2.4. Significance is a Poisson rule-of-thumb (|Δ| > 1.5√n), not a proper test.", camera: "Static chart", libs: [lib.canvas], load: () => import("../engines/triage/VersionCompare") },
    ],
  },
];
